### ISSUE TITLE
Not Responding Win 10 Pro

### ISSUE THREAD

**Issue by martymoose** [mjrgh/PinballY#1]
HI just installed as per readme
all i get is not responding  with kind of a window trying to open
also in admin mode as well
win 10 pro latest build 1803
2 screens + 1 topper screen
pin2dmd  device
pinscape + main expansion
is there a debug log i can post
![capture](https://user-images.githubusercontent.com/855823/43353421-492c9f24-927c-11e8-944f-22a6a062754f.PNG)

**Comment by mjrgh** [comment]
Okay, this should be fixed in the 1.0.1 Alpha 2 update.
