### ISSUE TITLE
Allow the "exit" menu to be editable to remove or add some options

### ISSUE THREAD

**Issue by rtl19** [mjrgh/PinballY#100]
I'd like the ability to choose whether 'power off' is in that menu.  I'm sure it'd be useful to have other options too.  I could see have a filter change option in that menu if desired.  (Just an example)

**Comment by mjrgh** [comment]
For that level of customization, Javascript is great.  This particular one is probably arguable one way or the other, but most of this kind of stuff is a little too "personalized" to make into a checkbox option in the dialogs - no one wants to have to wade through a billion checkboxes to find what they're looking for, so I try to restrict those to only the options that some fairly large percentage of people would probably use.

But it's really easy to control what's on the system menus from Javascript.  See "Overriding a system menu" under Javascript scripting > Events > Event Types > MenuEvent.

**Comment by rtl19** [comment]
Kk.  I'll have to look into that when I get a moment.  My mind was swirling on other nice menu options like having something off the operator menu that calls the pinscape configuration utility or the ipac setting utility or whatever.  Obviously these aren't very high up on the wish list.  Thanks for keeping an open mind!
