### ISSUE TITLE
Pinball FX2 Tables are not indicated when there are (parallel) FX3 Tables

### ISSUE THREAD

**Issue by fR33Styler-1971** [mjrgh/PinballY#102]
Hi there... first i like to say: very cool, i like your work very much (and switched vom PinballX to PinballY).

I just play FX2 and FX3 (no other Games).. 

and in FX2 there are 4 Tables which are not available in FX3:

- SplosionMan
- PlantsVsZombies
- SouthPark2
- SouthPark1

and all the (old) FX2 Versions like:

- Alien_Isolation
- Alien_vs_Predator
- ..
- .
- Western

in FX3 they are too, but for FX3:
from "Alien_Isolation" down to "WMS_White_Water"

Bug Description:

The 4 FX2 tables are not indicated... / not shown in the Frontend

Gamesetup is default: 
System class: STEAM
Program EXE: [STEAM]
Parameters: -applaunch 226980 "[TABLEFILEBASE]"
Window Mode: Minimize
Process name: Pinball FX2.exe
Table folder: steamapps\common\Pinball FX2\data\steam
Table extension: .pxp
DOF Prefix: FX2

It would be great if you can check this.

Best regards
Ralf

**Comment by mjrgh** [comment]
I'm afraid I don't have FX2 to test with, so you might be a bit on your own here.  Here are a couple of suggestions.  First, make sure that the games that aren't showing up have .pxp files in the FX2 data folder alongside the other files that do show up - the .pxp files are what PinballY keys on to build its list.  Second, take a look at the Troubleshooting page in the Help - there's a section on diagnosing problems exactly like this ("PinballY isn't finding my tables").  The first step there is always to turn on logging for table searches, and then carefully go over the log file - it explains the steps PinballY is taking during the table search, where it's looking, and what it's finding.  That usually explains these things.

**Comment by fR33Styler-1971** [comment]
thx for your fast answer.

I created the XML (in ..\PinballY\Databases\Pinball FX2) manually and now it works. Contend of the XML:

```
<menu>
	<game name="SplosionMan">
		<ipdbid></ipdbid>
		<description>Ms. Splosion Man (Zen Studios 2011)</description>
		<type></type>
		<rom></rom>
		<manufacturer>Zen Studios</manufacturer>
		<year>2011</year>
		<rating>3</rating>
	</game>
	<game name="PlantsVsZombies">
		<ipdbid></ipdbid>
		<description>Plants Vs Zombies (Zen Studios 2015)</description>
		<type></type>
		<rom></rom>
		<manufacturer>Zen Studios</manufacturer>
		<year>2015</year>
		<rating>0</rating>
	</game>
	<game name="SouthPark2">
		<ipdbid></ipdbid>
		<description>South Park - Butters Very Own Pinball Game (Zen Studios 2014)</description>
		<type></type>
		<rom></rom>
		<manufacturer>Zen Studios</manufacturer>
		<year>2014</year>
		<rating>3</rating>
	</game>
	<game name="SouthPark1">
		<ipdbid></ipdbid>
		<description>South Park - Super Sweet Pinball (Zen Studios 2014)</description>
		<type></type>
		<rom></rom>
		<manufacturer>Zen Studios</manufacturer>
		<year>2014</year>
		<rating>3</rating>
	</game>
</menu>
```



My Log now shows (FX2 related):

Configuring pinball player system "Pinball FX2"
+ database folder = C:\PinballY\Databases\Pinball FX2
+ [STEAM] executable specified, full path is C:\Games\Steam\Steam.exe
+ working path when launching player program is C:\Games\Steam\
+ full table path (folder containing this system's table files) is C:\Games\Steam\steamapps\common\Pinball FX2\data\steam
+ scanning for table files: C:\Games\Steam\steamapps\common\Pinball FX2\data\steam\*.pxp
+ media folder base name is Pinball FX2, full path is C:\PinballY\Media\Pinball FX2; this folder name was explicitly specified in the settings
+ searching folder C:\PinballY\Databases\Pinball FX2 for table database .XML files

+ System "Pinball FX2": loading table database file C:\PinballY\Databases\Pinball FX2\Pinball FX2.xml
++ This is the main file for this system (it doesn't define a category)
++ adding game Ms. Splosion Man, table file SplosionMan, media file base name Ms. Splosion Man (Zen Studios 2011)
++ adding game Plants Vs Zombies, table file PlantsVsZombies, media file base name Plants Vs Zombies (Zen Studios 2015)
++ adding game South Park - Butters Very Own Pinball Game, table file SouthPark2, media file base name South Park - Butters Very Own Pinball Game (Zen Studios 2014)
++ adding game South Park - Super Sweet Pinball, table file SouthPark1, media file base name South Park - Super Sweet Pinball (Zen Studios 2014)
High score retrieval: determining NVRAM path for Monster Bash

Looks great.

When iam ready with my VPIN 2.1 Update (some new toy´s, lights and a few updates) ill update [my documentation](https://www.dietle.de/status-report-project-vpin-self-made-virtual-pinnball/

) and create a video to... but for sure "i´ll stay with PinballY".. **you do a great job** - keep on pushing hard!! :)

Best regards from Germany
Ralf

**Comment by mjrgh** [comment]
Glad you figured it out!

For future reference, I think I know what was going on now.  You probably checked the checkbox **Hide unconfigured game** under the Game Wheel section in the options.  That tells PinballY to omit all games without XML records from the wheel display.  So PinballY was finding the .pxp files, but was leaving them out of the list, until you went and manually entered the XML data.

For that kind of situation, you actually don't have to enter the XML data manually.  All you have to do is allow PinballY to display unconfigured games.  That will include them in the wheel listings so that you can navigate to them, at which point you can use the Game Setup > Edit Game Details command to create the XML record through the GUI.  You can get unconfigured games to appear by un-checking the **Hide unconfigured games** checkbox in the options, or you can temporarily view **just** the unconfigured games via Operator Menu > Show Unconfigured Games.  The latter option is just a filter that selects only the unconfigured games, so that you can see everything that isn't set up yet in isolation.

**Comment by fR33Styler-1971** [comment]
Thx - this works for me, you can close this issue.
