### ISSUE TITLE
Is it possible to define custom loading images?

### ISSUE THREAD

**Issue by xantari** [mjrgh/PinballY#104]
**Describe the solution you'd like**
In PinballX you can put in loading image files and it will play that .gif (not sure if it's more than .gif's) while everything loads. Is that possible with PinballY? I didn't see anything in the documents about it.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by mjrgh** [comment]
Take a look at the help under

Javascript scripting > Worked Examples > "Seamless" Game Launch

Scroll down to the part about "Playing an animated overlay".  That'll explain how to do what you're after.

**Comment by xantari** [comment]
Excellent thanks!
