### ISSUE TITLE
Hotseat-Mode in Play-Dialog

### ISSUE THREAD

**Issue by fR33Styler-1971** [mjrgh/PinballY#106]
Hi again,

i know that Pinball FX can be startet with parameters "-hotseat_2, 3 or 4" in general by settings for systems.

But sometimes iam alone, sometimes with family and friends... so always a variation of player amounts.

Currently i start the game as single player and "esc" and switch each time from single to hotseat and start the game again.

I dont found the menu by myself (maybe its the optionsdialog.dll) but if i could i would extend the "play dialog" from
```

Play
-----
Information
----
Rate table
.....
```

to (kind of):

```
Play
Play Hotseat: 2 Player
Play Hotseat: 3 Player
Play Hotseat: 4 Player
-----
Information
----
Rate table
.....
```

Is there a way for me to do this or an idea for a feature request?
(maybe configurable for FX2 & FX3 Systems only)

I think the startparameters are already there..... just the "menu-point" is missing.

I look forward to read you feedback.

Best regards and keep pushing this great work, you do so much cool things for the community!!!

Best regards from germany
Ralf

**Comment by mjrgh** [comment]
Take a look at the help under Javascript Scripting > Worked Examples > Custom Play Modes.

**Comment by fR33Styler-1971** [comment]
Thank you, this points me to the rights place. Puh.. iam not a programmer.. but a know a little HTML and with trail on error and your examples i got it work (after 4 hours) :)

Iam sure a programmer can do much better.. but for me it´s working.

Best regards
Ralf

For all this can help (attached the main.js)
[main.zip](https://github.com/mjrgh/PinballY/files/4028446/main.zip)

**Comment by mjrgh** [comment]
Glad you got it going!  And thanks for posting your version.
