### ISSUE TITLE
Playfield preview not full speed 

### ISSUE THREAD

**Issue by Cley85** [mjrgh/PinballY#112]
Hi. 
I record all my video preview, but when i use it for playfield preview i have some frame drops. When i play it with vlc i have no problem and run in full speed. The only way to run my preview at full-speed is to disable the backglass preview. 
Thanks for your help

**Comment by mjrgh** [comment]
Is this the same thing as #90?

**Comment by Cley85** [comment]
> Is this the same thing as #90?

Nooo absolutely not, i have change my 75hz screen for a 60hz but bigger  😉

**Comment by mjrgh** [comment]
When you say "some frame drops", can you be more quantitative?

I kind of suspect the same thing that we were talking about with #90 - the vsync issue - unless you're on an entirely new system.  Especially since you said that thing about "unless I disable the backglass".  Sounds like another cross-monitor sync issue.

**Comment by Cley85** [comment]
Sometime the frame drop to 45fps and go back to 60fps after 3 or 4 second. And it's not at the same time in the video, it's random. I have play 2 vlc instance with 1 video and backglass, and the other 1 to playfield and it work. I use a gtx 1060 3gb ( new gpu, the old one was an amd hd 7850)

**Comment by mjrgh** [comment]
System load from other processes, then, perhaps?

**Comment by Cley85** [comment]
So you think i need to see in task manager if pinballY doesn't use all my resources?

**Comment by Cley85** [comment]
![Screenshot_20200404_094011_com facebook katana](https://user-images.githubusercontent.com/56386781/78421478-5a281f80-7658-11ea-9d6c-d42e5cd211ef.jpg)

As you can see, I'm not alone to have a problem with fps drops on playfield preview

**Comment by mjrgh** [comment]
I'm going to close this, since I don't think there's anything I can do about it (or really any way to investigate it).  If someone experiencing this wants to look into it, and if they can track it down to something actionable in PinballY, I'd of course be happy to consider a pull request for a fix.
