### ISSUE TITLE
LEDBlinky integration

### ISSUE THREAD

**Issue by xantari** [mjrgh/PinballY#113]
**Is your feature request related to a problem? Please describe.**
Pinball X has LEDBlinky integration built in. This allows to light up the proper buttons different colors upon launch of the software.

**Describe the solution you'd like**
Allow light up controls within LEDBlinky.

**Describe alternatives you've considered**
Not sure how to get the controls to light up without that? LEDBlinky has a front end option that lists PinballX as an option. Perhaps we also need to get that author to add this?

History:
My pincab uses a seperate Ultimate I/O Pacled64 based device for all button interaction and to light up the RGB buttons. The undercab and lightbar on my device is hooked up to a different PacLed64 device, and that is configured in DOF for all my cabinet toys, etc.

My initial thought would be to send LedBlinky the commands during different events using your javascript model. I do not see a PBYProgramExit command however to do the lightshow upon close of PinballY.

**Comment by mjrgh** [comment]
See also #114 - it covers a lot of the same questions, particularly about the shutdown event.

**Comment by mjrgh** [comment]
The Beta 20 adds DOF access to Javascript, so I think you can do everything you want here.  For the shutdown case in particular, see **Activating a DOF light show** in Javascript scripting > Worked Examples > Play a Video on Quit in the help.  But you can also trigger whatever other custom DOF effects you want using other event types - e.g., you could trigger a custom effect on selecting a new game, pressing a button, selecting a menu command, etc.

**Comment by xantari** [comment]
Thanks,

Quick question though.  My buttons on my cab are RGB buttons (Coin is RGB, left/right flipper and magnasave are RGB, and 3 more RGB buttons).  In DOF config tool I can see I can add my other PacLed device (1 is assigned to cabinet toys, the other is assigned to  buttons and button lighting).

I don't see how to define the RGB colors to buttons like you can for say Flasher Center?

**Comment by mjrgh** [comment]
> I don't see how to define the RGB colors to buttons like you can for say Flasher Center?

Short answer is you can't - the Config Tool thinks about those as monochrome lights.  I've suggested to Arngrim that it might be nice to extend those to RGB at some point, but I don't think many people use RGB lights, so there's not much demand for the idea (chicken and egg - no one installs RGB lights because DOF doesn't support them, and DOF doesn't support them because no one installs them...).  You *could* reassign them as Custom RGB entries, but that's a lot of work because you'd have to create custom triggers for all of your tables.

**Comment by mjrgh** [comment]
Closing, since it's accessible from JS now.
