### ISSUE TITLE
Add support for darker table previews

### ISSUE THREAD

**Issue by jsb2092** [mjrgh/PinballY#117]
It would be great if we could adjust the opacity on the table previews.  Often times, it's hard to see the wheel logo/artwork on top of the table.  If we could adjust the opacity of the preview it'd make them much easier to see when scrolling through games.

**Comment by mjrgh** [comment]
You're talking about making the table video semi-transparent?  Are you sure that would do what you want?  Because there's nothing behind to blend with except black - so partial transparency would be exactly like making it darker, like turning down the brightness proportionally to the transparency.  Does that really seem like what you'd want?  Maybe you'd be better off just doing a little Photoshopping of the icons that don't show up well enough, maybe adding a thick white border around them, or something like that?

**Comment by jsb2092** [comment]
The equivalent of adding a tinted piece of glass on top of the playing videos of the tables.

Love the program, was just adding a suggested feature.

On Feb 20, 2020, at 21:48, mjrgh <notifications@github.com> wrote:

﻿

You're talking about making the table video semi-transparent? Are you sure that would do what you want? Because there's nothing behind to blend with except black - so partial transparency would be exactly like making it darker, like turning down the brightness proportionally to the transparency. Does that really seem like what you'd want? Maybe you'd be better off just doing a little Photoshopping of the icons that don't show up well enough, maybe adding a thick white border around them, or something like that?

**Comment by mjrgh** [comment]
If you want to give that a try to see what it looks like, it's actually pretty easy in Javascript.  You just need to create a drawing layer in front of the backdrop layer, and fill it with semi-transparent black.  This isn't tested, but I think this is what the js would look like (just create a file called main.js in your PinballY\Scripts folder, and put this in it):

``mainWindow.createDrawingLayer(100).clear(0x80000000);``

The 0x80000000 part is an ARGB (alpha-red-green-blue) value with the fill color; 0x80 is 50% transparency.  You can experiment with different alpha values to see if you can find something you like.  This particular code will just create the drawing layer and leave it there permanently, but you could use a **gameselect** event listener to customize it on a per-game basis.  For more on all of this, see these sections in the help:

Javascript scripting > Drawing Layers
Javascript scripting > Events > Event Types > GameSelectEvent
