### ISSUE TITLE
menu pinbally options choose a system -> windows 10 crashes

### ISSUE THREAD

**Issue by wim312** [mjrgh/PinballY#12]
1.0.0 Beta 1 -64 bit on Windows 10:

menu-> pinbally options -> choose a system and windows 10 crashes

had no problem with release 1.0.0 Alpha 22

**Comment by sebinouse** [comment]
> 1.0.0 Beta 1 -64 bit on Windows 10:
> 
> menu-> pinbally options -> choose a system and windows 10 crashes
> 
> had no problem with release 1.0.0 Alpha 22

No problem on my setup

**Comment by wim312** [comment]
had some hardware GPU issues, 
after reinstall everythings works fine.

**Comment by mjrgh** [comment]
Great - thanks for the update!
