### ISSUE TITLE
Audio not muting correctly

### ISSUE THREAD

**Issue by jsb2092** [mjrgh/PinballY#120]
Update to #118 -  the issue is that the audio state resets when the table changes. If I have mute videos on one table, and change to another table, it's no longer muted even though the option is selected. Since the attract mode switches tables, the audio is not muted for that either.

**Comment by mjrgh** [comment]
D'oh, sounds like I missed a case - I'll take a look.

**Comment by jsb2092** [comment]
Fixed in Beta 22
