### ISSUE TITLE
Renaming a table should rename media files in RealDMD Color Images folder

### ISSUE THREAD

**Issue by jsb2092** [mjrgh/PinballY#123]
When renaming a table, the media files in ReadDMD Color Images do not get named.

Step 1. Rename a table (The Addams Family to Addams Family, The)
Step 2. Get notification about renaming media

What happens
File in RealDMD Color Images is not renamed.

What should happen:
File in Real DMD Color Images should be renamed the same as other hyperpin media.

**Comment by mjrgh** [comment]
Sure enough - all of the real DMD media and launch audio files were missed.  I'll fix that for the next update.

**Comment by mjrgh** [comment]
Should be fixed in Beta 23.
