### ISSUE TITLE
No table sound on b22

### ISSUE THREAD

**Issue by sverrewl** [mjrgh/PinballY#124]
Ref. earlier closed issue 121.

Now, with build 22, I don't get any table audio at all. So, the 30ms didn't work for me at all - it seems to even worsen the issue. As I said. Almost all samples are 35 seconds long or around that. I counted slowly to 50 - probably longer than 50 seconds. No table audio. Renaming the 20 build exe only and it works without changing any of my options.

**Comment by mjrgh** [comment]
Very strange - it's working perfectly on my end.  I'm out of ideas - without being able to reproduce it here, I'm not sure how to approach it.  Any chance you can do a source build and look at it in the debugger?

**Comment by sverrewl** [comment]
I'm not very keen on installing vc on my cab, it has already too much odd stuff installed python27, perl5.24 with different and similar mingw dependencies. I still must admit, haven't tried it on my desktop machine. Will do soon. But, there was something that made me start to ponder a couple of days back. I had issues with audacity after updating mother board drivers for sound. I have a 4:1 with sub solution there. Audacity would not capture over WASAPI and loopback before I change the count for the streams from 2 to 4 - see attached screenshot. I mentioned a long time ago that I didn't see loopback as an alternative on my cab. It is named exactly the same as above on that machine and the realtek motherboard drivers there are working as they should.  https://www.dropbox.com/s/71i4vcmupgz47fc/Capture.PNG?dl=0

Could it be that this is the reason why I can't capture table sounds ? The name is kind of filtered out ? I don't expect I'm the only SSF user that runs PBY, but, It just makes me wonder, could maybe my issue be related to having 5:1 setup on my cab/VP ?

**Comment by sverrewl** [comment]
So, I installed (updated) latest on my Desktop machine - no room for all the media and tables, but, I copied launch, audio and wheels and copied over settings too. After adjusting this back to a one screen. I could scroll through the tables with wheels etc, but, no sound. Copied the r20 release exe from my backup of my cab and now I see the exact same thing happening. Table sound plays while scrolling. This is a good thing, I've already got vc installed on this machine ... somewhere - only used it once to compile db2sserver a while ago. Never really used it before, so when you say debug - is that something I'll be able to figure out ?? Maybe I could lure you into compiling a version for me ?

**Comment by sverrewl** [comment]
Oh, yeah. Should mention. I switched my sound output from Quadraphonic to Stereo while testing, didn't change anything. Still have a feeling though it might come into play IF we're talking about recording.

**Comment by sverrewl** [comment]
Wow. Got some kind of progress I guess. I took the old - original settings.txt backup file that I had. Just changed the media and database to point at pinballx like I have on my cab and the latest version now is giving me table sounds. Now to figure out what is making this croak. https://www.dropbox.com/s/z399qfrw17uv0rw/Settings.txt-cab?dl=0 ( cab settings.txt ) - working settings.txt https://www.dropbox.com/s/xx0o930itishnh6/Settings.txt?dl=0 if you are finding this interesting.

**Comment by sverrewl** [comment]
Video.MasterVolume = 10

I believe this is the culprit, did some comparing and adding things I had in my cab, one by one until it broke.

**Comment by mjrgh** [comment]
> Video.MasterVolume = 10
> 
> I believe this is the culprit, did some comparing and adding things I had in my cab, one by one until it broke.

Aha!  That would certainly do the trick.  That's a percentage volume, so 10% is practically inaudible, and would explain why you're not hearing anything.  The audio tracks were playing but were just practically muted by the 10% volume level.    It would also explain why it only affected versions from Beta 22 onwards, since that's where I fixed the earlier problem where the master volume wasn't always being applied properly.  You had probably tried different settings for the master volume (via the Audio/Video settings page) in some earlier version while trying to find a workaround for that earlier bug.  So when it started getting applied properly in Beta 22, it was having the effect of muting the audio by turning it down to a nearly inaudible 10%.

**Comment by sverrewl** [comment]
Ah. Happy to hear that it all makes sense again :+1:

**Comment by sverrewl** [comment]
Just curious, any insight to if my device isn't capturing ? It is a loopback - from the speakers as I mention. Hmm. Maybe I should make that a new case ?

**Comment by mjrgh** [comment]
> Just curious, any insight to if my device isn't capturing ? It is a loopback - from the speakers as I mention. Hmm. Maybe I should make that a new case ?

I don't have any guesses off-hand, and I agree, it might be better for future reference (for the sake of other people searching the issue list for similar problems) to create a new issue for that.

**Comment by sverrewl** [comment]
And, I've now tested that volume change on the cab and you can close this thread. Works like a charm and are now finally on 1.0 ;) :+1:

**Comment by mjrgh** [comment]
Great!
