### ISSUE TITLE
mame xml request

### ISSUE THREAD

**Issue by d8thstar** [mjrgh/PinballY#127]
i am building arcade controls into my machine and already have MAME up and running thru PinballY, excellent (vertical screen only games)
 
it would be FANTASTIC if PY could read a mame.xml file correctly so we wouldn't have to go into each games set up to change the name/manufacturer/year and so that the correct name displays (Donkey Kong instead of dkong).
 
i'd happily pay for this feature!  and if you are taking donations, please let me know where I can pitch in!

**Comment by mjrgh** [comment]
What kind of XML files?  Are you talking about HyperPin/PinballX XML files?  If so, that should already be supported.  Try reading through the help sections on [System Setup](http://mjrnet.org/pinscape/downloads/PinballY/Help/SystemOptions.html) and [Files & Folders](http://mjrnet.org/pinscape/downloads/PinballY/Help/DirectoryInfo.html) - it should just be a matter of pointing PinballY to your existing XML database file.

**Comment by d8thstar** [comment]
thank you for the response!  yup, followed those directions, added new system “arcade games”.  i have a media folder, same name, working because the media for the arcade games is showing in pinbally.

within the database folder is an “arcade games” folder and an “arcade games.xml” file in that.

fyi, i tried a few different xml’s, one downloaded from hyperSPIN and another generated my mame (but i did rename the xmls to “arcade games” before trying.

trying a few different things but coming up short.

**Comment by mjrgh** [comment]
It's often helpful when troubleshooting these things to turn on logging for "Player system setup and table searches" (in the options under the Log File page).  Then exit out of the program, run it again, exit out again, and carefully look through PinballY.log to see where it's looking for XML files and which files it's finding.

**Comment by d8thstar** [comment]
forgot to mention, it’s the info box where the game name is showing as the rom name.

**Comment by d8thstar** [comment]
i’ll give it a shot and report back, thank you!

**Comment by d8thstar** [comment]
only thing i see is a “no system class specified” and a few other lines dealing with no system class.  that said, the log shows that it finds my zips and it also shows that it finds the media with the full game name (not truncated rom name).

so it’s just that info window and i really don’t want to go to game setup to change 800+ names :)

**Comment by mjrgh** [comment]
1. Just to be sure, you've identified specific lines in the log script that say that PinballY is loading the XML file you want it to load?  I mean you found information in the log file calling out that XML file by name, saying it was loaded successfully?

2. Maybe post a screen shot of the info screen you're talking about, so I can be sure we're talking about the same thing.

**Comment by d8thstar** [comment]
1. yes sir.  it’s parsing my media folder and displaying real world game names along with the rom name.

2. it’s just the small info screen that appears above the wheel when scrolling thru games.

i actually just tried deleting the system and reading but it’s still bagging the same.

this is odd, it obviously is parsing the xml, just not displaying the name correctly in the info window.

happy to post a log file if you think that might help?

really appreciate this man, great piece of software!

**Comment by mjrgh** [comment]
Okay, so the name that appears in the title in the info box comes from the `<description>` field in the XML.  What does your XML have for `<description>` for the games in question?

**Comment by d8thstar** [comment]
ok some progress, one step forward two steps back!

so i has all mame artwork displaying, only thing that needed attention was the info box name.

so, i deleted that system and started over, renamed it MAME.  i then went into the xml, did a blanket find/replace on manufacturer and year.  now game names are appearing normally!

but, now the artwork is appearing correctly.  looking at the game details for donkey kong, the name is correct but the last line for “media name” also says donkey kong when all artwork is named for the rom name dkong.

game details window, very top, starts with the file name, dkong.zip.

if i could find where pinbally is filling in that media field from, seems to be defaulting to the description.  if i could force that field to duplicate the rom name for itself, i would be 100% golden!

any help is appreciated man!

**Comment by mjrgh** [comment]
The help section [Files & Folders](http://mjrnet.org/pinscape/downloads/PinballY/Help/DirectoryInfo.html) explains how the media name is constructed.  Read "Media files for each game".

**Comment by d8thstar** [comment]
right on.  i mean i know o can do that i was just hoping for an easy way to make a bulk change ca having to go into each games game detail dialog but if that’s the only way, i better get started :)

thanks for being a sounding board and listening

**Comment by mjrgh** [comment]
If I were you, I'd probably set up a script that updated the XML files rather than doing it all manually.  You might even be able to rig something with the Javascript engine in PinballY itself, actually.  You can access and update all of the game metadata from Javascript, so you could probably set up something that would automatically check the current game's metadata and fix it up when the game is selected.  Some help sections that might be relevant to setting that up:

[Javascript scripting > Events > Event Types > GameSelectEvent](http://mjrnet.org/pinscape/downloads/PinballY/Help/GameSelectEvent.html)
[Javascript scripting > System Objects > gameList](http://mjrnet.org/pinscape/downloads/PinballY/Help/GameList.html)
[Javascript scripting > System Classes > GameInfo](http://mjrnet.org/pinscape/downloads/PinballY/Help/GameInfo.html) ("Updating game metadata" especially)

**Comment by d8thstar** [comment]
ah!  you are assuming i’m that smart :)

nope!

**Comment by d8thstar** [comment]
hey mj,

anychance you could draft up a jsca script to do the requested?  go into the PY back end and either 

1. rename the game media name to the game rom name?

but you want to be able to pick which database you are running the script on.

i know you are busy so i’m offering some finds to help out, just let me know if you are interested.

thanks again for all the hard work on this!

**Comment by mjrgh** [comment]
Maybe try asking on the forums - if you can state the problem precisely enough, someone can probably come up with the Javascript.

**Comment by d8thstar** [comment]
hey mj,

just to try something else, i installed PinballX which does display mame names correctly with files named as is.

personally, i want to stay with your app, i find it easier to use and it loads tables much quicker!

i may just have to go thr route of editing all my mame rom descriptions / media name but in the end it'd be worth it.

i did notice something, in the game detail screen, you have file name (which can't be edited), titla, rom name and media name.

for me to make my edits, i have to go in once, change the media name from [default] to the rom name and click ok.  then i have to go back in and the title has changed to the file name and i have to edit that on the second pass.  it's odd that it doesn't "stick" on the first edit.

anyways man, i hope that this is something that can be addressed.  i am sticking with Y, just hoping you could look at teh way it's parsing mame names.

awesome piece of hardware, please keep it up!

**Comment by mjrgh** [comment]
You've come across an interesting problem with the title update!  The XML schema from PinballX/HyperPin doesn't actually have a way of separating the title and media name - it's all kind of mushed together in the `<description>`.  So when you go into the Game Details editor and change both of them, things get a little confused in the XML, or maybe I should say, the PinballY code that updates the XML gets a little confused, because it can't actually represent both changes at the same time with the XML schema as it is.  So it turns out that the title update gets lost in the XML.  

I think I'm going to have to extend the XML schema to add a separate, independent `<title>` element so that the title can be changed separately.  I've really tried to keep the XML schema 100% compatible with PinballX/HyperPin so that people can migrate the XML files back and forth between the programs, but I think an extension to the schema is warranted here.  I'll look into adding that.

In the meantime, if you want to get it going within the current schema, what I'd suggest is that you basically do what PinballY expects with the naming, and don't try to set the media names and titles to be different.  What that means for you is renaming your media files to conform to the PinballY convention of using "Title (Manufacturer Year)" for all of the media file names.  PinballX lets you use **either** the table file name **or** the "Title (Manufacturer Year)" format for media naming, but I made a deliberate decision with PinballY to **only** use the one format "Title (Manufacturer Year)", to avoid the confusion and ambiguity that the dual convention creates.  It sounds like you picked the "other" convention in PinballX, which unfortunately makes for this migration hassle for you.   But at least it's a mechanical change that you should be able to automate. 

If you can give me the following information for a random selection of games, I can probably write you up a little Javascript that will do the media renaming automatically:

- the full XML entry for the game
- the name of all of the game's media files **as they exist now on your disk**

Give me that for maybe three or four randomly selected games, so that I can see the exact pattern of the files you're using, and I think I can give you the needed Javascript to rename the files.

**Comment by jsb2092** [comment]
@mjrgh this is one of the reasons that xml is annoying. Lack of flexibility.  That being said, I can't imagine the use case of people wanting compatibility back is high, but maybe give them option of 'upgrading' would be a good option.

**Comment by mjrgh** [comment]
> this is one of the reasons that xml is annoying. Lack of flexibility.

Well, I think in this case just the opposite applies, as XML is infinitely flexible here to add new things like this to an existing schema. The main compatibility question is whether PinballX's XML parser is flexible enough to accept tags that it doesn't know about (which isn't really an XML issue).  PBX being closed source, it's not clear what it's doing internally, but empirically it doesn't seem to have problems with random added tags I've tried against it.  That being the case, there's really no "upgrade" option needed; it's just that PinballX would ignore the information in added tags, so it would be compatible in the sense that it would accept the XML; it just wouldn't use the new information.  So the way I see it, it's a net win that HyperPin/PinballX used an inherently extensible format like XML here rather than some non-extensible ad hoc format of their own.

**Comment by jsb2092** [comment]
I find JSON to be infinitely more flexible, but that's because the libraries are usually well written, but that's water under the bridge.

**Comment by mjrgh** [comment]
> I find JSON to be infinitely more flexible, but that's because the libraries are usually well written, but that's water under the bridge.

Indeed, this is obviously off on a wild digression (maybe it would be better to file a bug against the XML consortium for "your third party library support are suck"?), but for what it's worth, I think you can see that there would be zero difference for our purposes here if HyperPin had chosen JSON.

**Comment by jsb2092** [comment]
Yes, I derailed the bug, I'll delete my comments.

**Comment by d8thstar** [comment]
hey man,

i realy appreciate you willing to look into this!  for the test, lets take the three donkey kong games, xml data is below.

I set up a special folder in which i copied over the three donkey roms, dkong.zip, dkong3.zip and dkongjr.zip.

also within that same folder, i have copied over the wheel image, dkong.png.  keep in mind, if you write a scirpt, the end user will only be able to change one piece of media ata time since all of teh art for the game is named the same and it's distinguished by the folder it's in.  I am absolutely fine with that!  i just thought i would point it out!

so now this folder has roms, dkong.zip, dkong3.zip, dkongjr.zip and wheel art for all three, dkong.png, dkong3.png and dkongjr.png (that png can obviously be another extension, if converting videos for instance, .mp4

so whatever script would need to look at the below xml find the rom name (game name), find the name matched media file (same name, whatever extension) and rename that file to the "description" line of the xml

i found launch times painfully slow in pinballX and really really love Y very much, it has been a pleasure setting up my new build with your software!

i apologize if i have been a pain, this new build is SO close to being done and if i can get this mame stuff ironed out, you will have made a happy camper :)  

here is the xml for the three games:

`</game>
	<game name="dkong" index="" image="">
		<description>Donkey Kong</description>
		<cloneof></cloneof>
		<crc></crc>
		<manufacturer></manufacturer>
		<year></year>
		<genre></genre>
	</game>
	<game name="dkong3" index="" image="">
		<description>Donkey Kong 3</description>
		<cloneof></cloneof>
		<crc></crc>
		<manufacturer></manufacturer>
		<year></year>
		<genre></genre>
	</game>
	<game name="dkongjr" index="" image="">
		<description>Donkey Kong Junior</description>
		<cloneof></cloneof>
		<crc></crc>
		<manufacturer></manufacturer>
		<year></year>
		<genre></genre>
	</game>`

**Comment by mjrgh** [comment]
Thanks - that's exactly what I figured your setup looked like, but I wanted to make sure I had the right picture in my mind.

Here's a script that will do the renaming.  

**Before you do anything else, make a full backup copy of your entire media folder tree.**  This script will rename files as it runs, so if anything goes haywire, it could make a terrible mess of things.  I want to make absolutely sure you have a complete backup that you can restore if it screws up - I don't want to make the situation worse!  Put the backup somewhere safe, ideally on a removable external disk or a cloud server account - somewhere that an errant script won't be able to reach it.

Once you're sure you have a solid backup tucked safely away, create a file in your PinballY\Scripts folder called Main.js, and copy the contents below into it.

Now run PinballY (be sure to exit out of any old session first).  Simply go through all of your games in the wheel.  Each time you visit a game in the wheel, the script will check to see if the media for that game exist under the "old" naming convention, and if so, it'll rename the old name to the new name.  It does this **as you select each game**, so you'll just have to scroll through your entire collection, one game at a time, to update everything.  After you've gone through it once, the files should all be renamed, so you can remove the script.  The script will probably slow down scrolling slightly, so it's not something you'll want to leave permanently installed - just make one complete pass through your collection to rename all files, and after that you shouldn't need the script any more.

```
// Automatic media file renamer
//
// Copy this into a file called Main.js in your PinballY\Scripts folder.
// Exit out of PinballY if it's running, and restart it.  As you scroll
// through your games, this script will check each game as it's selected
// in the wheel to see if the game has any media files under the expected
// media file name, using the "Title (Manufacturer Year)" naming rule.
// If no such files are found, it'll look to see if the game has any media
// files under the alternative PinballX convention, which lets you name
// media files the same as the raw table file name (in the case of MAME
// video games, this is typically the name of the MAME ROM file).  If
// so, the script will automatically rename the files to match the
// "Title (Manufacturer Year)" convention.
//
// Note that this might slow down scrolling through the wheel UI a bit,
// so you'll probably want to install this script only long enough to go
// through all of your games once (one at a time).  The file renaming is
// permanent, so you should only need to make one pass through an existing
// collection.  You can then remove the script for normal use.
//
gameList.on("gameselect", ev =>
{
    // get the game
    let game = ev.game;

    // If this game is configured (i.e., it has an XML database entry),
    // check for media.
    if (game.isConfigured)
    {
        // Note the current, "standard" media name.
        let stdMediaName = game.mediaName;
        
        // Figure the "alternative" PinballX naming convention for the
        // game's media, based on the table file name.  The table file
        // name sometimes includes the system extension and sometimes
        // doesn't (PinballX's setup tool seems to be inconsistent
        // about this, so PBY allows it either way).  So check for the
        // default extension, and remove it if present.
        let altMediaName = game.filename;
        let ext = (game.system || {}).defExt;
        if (ext && altMediaName.endsWith(ext))
            altMediaName = altMediaName.substr(0, altMediaName.length - ext.length);

        // If the alt media name doesn't match the standard media name
        // (using the "Title (Manufacturer Year)" convenion), check for
        // media that need to be renamed.  There's no point in checking
        // for media if the alt name and standard name are the same, as
        // we'd just be renaming from X to X.
        if (altMediaName != stdMediaName)
        {
            // Let's find out if there are any existing media files under
            // the "right" media name, via a sneaky trick.  Changing the
            // media name in the GameInfo object will hand us back a list
            // of the game's existing media files under the *old* name,
            // to give us a chance to rename them.  If this list has any
            // entries, we'll know that there are existing files.  We
            // don't *really* want to change the game's media name - this
            // is purely to probe for the existence of the files.  However,
            // it also has a handy side effect, which is that if we change
            // the name to the "alt" name, and then change it *back*, the
            // change back will give us the same information about extant
            // media files under the "alt" name.  So, step 1: change the
            // media name to the "alt" name, WITHOUT actually renaming any
            // existing files, purely to probe for existing files.
            let update = game.update({mediaName: altMediaName}, {renameMedia: false});

            // Step 2: let's see if the game has any existing media under
            // the "normal" name.  If it did, the update results will have
            // a list of one or more files that need to be renamed to match
            // the media name change we just made.
            if ((update.renamedMediaFiles || []).length > 0)
            {
                // The game DOES have media files under the "standard"
                // name, so we don't want to rename anything after all!
                // Simply restore the original media name, and we're done.
                game.update({mediaName: stdMediaName}, {renameMedia: false});
            }
            else
            {
                // The game DOESN'T have any media files under the "standard"
                // name.  So the question now is: does it have any media
                // files under the "alternate" name?  If so, we'll want to
                // rename those files to the "standard" name.  Luckily,
                // thanks to the media name change we just made, the next
                // step is practically trivial.  Since the game's media name
                // is now the "alt" name, renaming it BACK to the "standard"
                // name will have the effect of searching for extant media
                // files under the "alt" name and renaming them to the
                // "standard" name.  In this case, we'll let the update()
                // function do the renaming for us.  Note that we don't even
                // have to make any extra checks for extant files here; the
                // mere act of updating the media name from "alt" to "std"
                // will have the desired side effect of renaming any media
                // files that exist under the "alt" name, and won't do
                // anything if not.  And it also puts things back in their
                // original state for the game's metadata, so two birds, one
                // stone!
                game.update({mediaName: stdMediaName}, {renameMedia: true});
            }
        }
    }
});
```

**Comment by d8thstar** [comment]
oh man!  i can’t wait to give this a spin!  thanks so much man, i will report back once i get a chance.

i’m assuming just a notepad file saved as Main.js would work?

**Comment by d8thstar** [comment]
oh man!  i think you may have nailed it!  all of the wheel images that were just plain text started popping in!

even some videos started appearing.  i need to do some more testing to figure out why all videos aren’t popping up but totally on the right track!

thank you man!  can i please buy you a pint of four with some paypal love?

**Comment by mjrgh** [comment]
Great, glad to hear it's helping make some progress.  Hopefully the remaining videos are just a matter of variations in naming or something like that, and hopefully it's getting down to a manageable number that some manual renaming or file moving will take care of.

(Thanks for the paypal offer, but not necessary!)

**Comment by d8thstar** [comment]
just a quick update, it's working but not at 100%.

does the app check all media folders fr the selected system/game?  as an example, "Noah's Ark" is the description, rom name is noahsark.zip 

after running your script the wheel image changed perfectly.  checking the folder, the file name was changed as it should have been.

but checking my Table Video folder, i still see noahsark.mp4, the file name was not changed.

thanks again for your willingness to help, as always!

**Comment by mjrgh** [comment]
Yes, it should have gotten all media types.  The exception would be if you had manually renamed ANY of the files for a given game, since it will only do the search if the game has NO files at all initially.  So if you manually renamed any of the files at any point, that would prevent the script from looking for the others for that game.

**Comment by d8thstar** [comment]
thanks for teh info, I know i had started renaming but i'm pretty sure i never touched noahsark (im just using tat as an example).

so what if I wanted to start from scratch and let your script do all the heavy lifting?  would deleting the mame.xml be enough or are things tagged in the back end of pinballY and I would need to do a reinstall of pinballY to get that fresh start?

**Comment by mjrgh** [comment]
I don't think you'll want to delete the XML file, since that's where all of the metadata (title, manufacturer, year, etc) are stored - if you got rid of that, you'd have to enter all of that again manually.

It would actually be pretty easy to modify the script so that it skips the check for the "new" media names, and renames the "old" names even if there are already some new ones out there.  That might be all you need, at least to take care of most of them.  (I wouldn't be surprised if you have a few outliers with names that don't quite match the "new" or "old" names, given your large collection.)

If you want to give that a try, here's the modified version (it actually makes the script quite a lot simpler):

```
gameList.on("gameselect", ev =>
{
    // get the game
    let game = ev.game;

    // If this game is configured (i.e., it has an XML database entry),
    // check for media.
    if (game.isConfigured)
    {
        // Note the current, "standard" media name.
        let stdMediaName = game.mediaName;
        
        // Figure the "alternative" PinballX naming convention for the
        // game's media, based on the table file name.  The table file
        // name sometimes includes the system extension and sometimes
        // doesn't (PinballX's setup tool seems to be inconsistent
        // about this, so PBY allows it either way).  So check for the
        // default extension, and remove it if present.
        let altMediaName = game.filename;
        let ext = (game.system || {}).defExt;
        if (ext && altMediaName.endsWith(ext))
            altMediaName = altMediaName.substr(0, altMediaName.length - ext.length);

        // switch to the "alt" media name - don't rename any existing
        // files with the "standard" name, just switch the name so that we
        // can look for files with the "alt" name
        game.update({mediaName: altMediaName}, {renameMedia: false});

        // Switch the name back to the "standard" name, and this time,
        // rename any files we find with the old name.  This will change any
        // "alt' name files to the "standard" name.
        game.update({mediaName: stdMediaName}, {renameMedia: true});
    }
});```

**Comment by d8thstar** [comment]
DUDE!  you just got me 95% there!  thank you thank you thank you thank you!

**Comment by d8thstar** [comment]
hey mj,

i didn’t want to start a new ticket since this is sort of related...

thank you for the above!  i got that grouping of mame (vertical games) all sorted with your help.

just for giggles, i added a “new” platform, this time “MAME209” with all of the appropriate set up in pinballY options.

but this new set of roms is only showing up when viewing uncategorized games.

so my question is how does Y “categorize” games?  when first starting on a newly added platform, does each game need to be gone into the game edit screen so that the info “takes”?  is there anyway to blanket categorize all games?  this new install of mame is 11k+ titles and that would take forever to go into each game edit.

thanks again for everything man!

looking at the xml and the game set up screen in Y, all of the info seems to be there.

**Comment by mjrgh** [comment]
You can just ignore categories if you don't want to assign them.  "Uncategorized Games" is a filter that selects all games without categories, so if you haven't assigned any categories to any of your games, that's why they're all showing up when you select "Uncategorized" Games.  They should ALSO show up under filters that don't have anything to do with categories, such as "All Games" or "Mame209 games".

**Comment by d8thstar** [comment]
apologies!  replace uncategorized in my post with unconfigured.

**Comment by mjrgh** [comment]
Ah, okay.  "Unconfigured" means that the games don't have any metadata entered - that is, the XML files.  So yes, I'm afraid you'll have to enter all of that by hand if you don't already have the XML data somewhere you can plug in.  If you do already have XML files for the games, it's the same procedure as before to tell PinballY where to find the XML files.

**Comment by d8thstar** [comment]
yeah, the xml looks fine to me.  all games have their info correct in the xml and the game edit window so not sure why they show as unconfigured.

i’ll just use your excellent script again :)

**Comment by mjrgh** [comment]
Hmm, if the metadata is showing correctly in the Edit Game Details dialog, then the program is definitely reading the XML okay, and that's pretty much the definition of "configured".  So I'm not sure why they'd be configured in the one sense and not configured in the other sense.  You're saying they ONLY show up when you select the Unconfigured filter?

**Comment by d8thstar** [comment]
yeah man, it’s got me confused!  i should be home in a few hours.  i will snap a couple of pics, zip them up and post so you can see what i’m talking about.

**Comment by d8thstar** [comment]
so here is the info i have.  pics attached,

pic - shows "no table" - this is me selecting system "mame209"

pic - shows the game edit screen for "defender"  all pertinent fields filled in

pic - shows the defender named video i have for table video.  you can see that the path is correct

pic - shows pinballY option screen for the added system, mame209

and here is the xml part about defender:

<game name="defender" index="" image="">
		<description>Defender (Red label)</description>
		<cloneof></cloneof>
		<crc></crc>
		<manufacturer>Williams</manufacturer>
		<year>1980</year>
		<genre>Shoot-'Em-Up</genre>
		<rating></rating>
		<enabled>Yes</enabled>
	</game>
[Desktop.zip](https://github.com/mjrgh/PinballY/files/4489975/Desktop.zip)

**Comment by mjrgh** [comment]
First off, you've gone through the Troubleshooting section in the help under "PinballY isn't showing media for my tables", right?

**Comment by d8thstar** [comment]
rtfm.... i know better!   i'll report back my findings.

**Comment by d8thstar** [comment]
yeah, everything looks fine,  it is showing media because of the same issue as first reported and that your excellent scrip fixed for me.

im just curious why mame209 is showing as unconfigured when in the pics i posted, you can see that they should show as configured...

anyways, thanks for everything man, i really appreciate the tie youve spent with me

**Comment by mjrgh** [comment]
I'm at a loss for what's going on too.  Just to be sure I know what you're doing in detail, maybe you could lead me through the exact set of menu clicks you're making?  Extreme detail - I want to make sure I'm not missing anything.  (I obviously can't see what you're doing from here, so I can only guess unless you give me every mouse click in agonizing detail.)

**Comment by d8thstar** [comment]
hey mj,

would you be willing to do a 10-20 minute team viewer session?  i’m not looking for any special treatment, just want you to be able to see that i’m not crazy :)

**Comment by d8thstar** [comment]
just a quick update...  

i deleted the new system and started again.  couple of things:

- games are showing but only as hidden

- all games that are in the rom folder are being shown (12k+) even though the xml i have for this new system is curated down to just under 3K games

- your script is still working brilliantly and renaming media appropriately

so, is there anyway to blanket unhide games?  if i can get them all unhidden, i might be able to find some tool that will move oms that are not in the xml.

as always, thanks for the great app!

**Comment by d8thstar** [comment]
so its official, i'm an idiot.  it was parsing all xml's in the folder, even though i renamed xmls to try new ones.  deleting all but the xml i wanted reduced my list to 3900 games.

now if i could just get them to show as not hidden

**Comment by mjrgh** [comment]
Could you clarify what you mean by "hidden"?

**Comment by d8thstar** [comment]
for sure.  main screen, i filter by system and select "mame209".  that then only shows "no tables".

if i press zero, i can select "show hidden games".  on this list, i can see all 3900 mame209 games!  in the game edit screen for each game, they all seem to be configured and your script does its magic to change media to fit the game.

its just that they are on this hidden list.

**Comment by mjrgh** [comment]
That's curious - "Hidden" is a special status that you have to explicitly assign to a game.  Nothing is ever hidden by default.

Any chance that you went through them and hid them manually somehow?  It's easy enough to unhide them manually - Operator Menu, Game Setup, Un-check "Hide this game".

If you look at GameStats.csv (in the PinballY main folder), under the Is Hidden column, do you see them all show up with "Yes" there?

**Comment by d8thstar** [comment]
weird one...

100% positive i didnt hide 12k games manually :)

looking at the csv, it doesnt even show mame games.

went into the operators menu, game set up.  i can select "hide game" on this already hidden games and they fall off the hidden list i am in.

if i then unselect "show hidden games", the no table thing comes back.  reselecting show hidden games, shows the 3900 games back again along with the game that i manully hid.

while in hidden view, operators menu does not have "unhide", it only allows me to hide again.

just an odd one i tell you but i can live with it!

**Comment by mjrgh** [comment]
> while in hidden view, operators menu does not have "unhide", it only allows me to hide again.

Just to clarify that, there's no such command as "unhide" - it's always "Hide this game", and it either has a checkmark or not.  So if it's hidden, it'll have a checkmark next to it in the menu, and selecting the menu will remove the checkmark.

**Comment by d8thstar** [comment]
sorry yes, i was typing from memory.  at my machine now.  i have "show hidden games" checked, meaning, i am seeing all game that are hidden.

now if i go into the operators menu, game setup, the option to hide the game is there, meaning, its not checked.  i would think if i am viewing all hidden games, that in game edit, "hide this game" would also be checked; unchecking it would unhide the game.

**Comment by mjrgh** [comment]
I think I know what's going on!  I forgot that the "hidden" flag can also be set in the XML via "enabled":

`<enabled>false</enabled>`

I'm guessing you probably have that set in the XML for all of these games.  Looking at the code, the `<enabled>` status in the XML is respected when deciding which games to show, but it's not consistently respected in all of the other places it might matter, such as deciding whether to show the checkmark for "Hide this game" in the Operator menu. 

I'll fix the inconsistent handling for a future update, but in the meantime, I'm not sure what the easiest solution for you is.  If it were me, I'd just do some bulk-processing of the XML to delete all of the `<enabled>` flags en masse, maybe by opening the file in a text editor and doing a global search-and-replace.

**Comment by d8thstar** [comment]
so i wake up this morning and have to try this out before i leave for work...

i opened my mame209 xml, but see that all of <enabled> flags are set to yes.  i do a find/replace so the line reads <enabled><enabled>.  nothing happens.

one more try, i change them to say <enabled>true<enabled>.

BOOM!!!!!  i now have my filtered list as unhidden  games and your wonderful script to help me with the media renaming and all is right in the world!

thanks again man for not giving up and finding the solution!

my offer for those paypal pints is always open to you!

**Comment by mjrgh** [comment]
> i opened my mame209 xml, but see that all of flags are set to yes
> one more try, i change them to say true.

Aha!  That looks like another change I should make - I'll change it to accept YES instead of just TRUE.  I've only seen the PBX tools generate that tag with TRUE before, but there must be some inconsistency among the tools.  Easy enough to accept both.

Glad you got it working!
