### ISSUE TITLE
high fps

### ISSUE THREAD

**Issue by toccata10** [mjrgh/PinballY#13]
1st of all: thanks for this project: it looks very promising (and open-source!!).
I'm testing on a win10-x64, with a amd r9 fury, with just 1 screen (desktop mode): I have very high fps (over 1 000!), and so the gpu starts getting hot.
I tried to limit with the radeon control center, but no luck: my value is not taken into account.
It would be nice to have an option to set the max fps (although 60fps could be ok for everyone).
When I right click, the fps seems to drop to a more reasonnable rate.

**Comment by mjrgh** [comment]
Okay, I'll look into adding an option to limit the rendering rate.

**Comment by mjrgh** [comment]
I've added an option for the next update that lets you sync to the monitor's physical refresh rate.  It'll appear under the Audio/Video section in the Settings dialog.

**Comment by mjrgh** [comment]
Should be fixed now in the Beta 2 release.
