### ISSUE TITLE
PNG images not transparent on topper or dmd screen

### ISSUE THREAD

**Issue by miguelcerca** [mjrgh/PinballY#132]
I've got a few tables that I would like to have an overlay on the topper and dmd area when the table loads. i've created transparent png files for these areas, however they are not transparent, the transparent areas are black and do not let the images/videos from the tables show through.

**Comment by mjrgh** [comment]
Could you be any more specific about what you're doing?  Test case, step by step (keystroke by keystroke/mouse click by mouse click) instructions are helpful.  

https://github.com/mjrgh/PinballY/wiki/How-to-write-a-good-bug-report

**Comment by miguelcerca** [comment]
Sorry for the bad explanation...hopefully I can make it more clear this time.
In order to test, i've changed the Windows background color of all my screens to bright red.
I've created a PNG image that I would like to act as a border on the topper screen.
The border has images, the middle of the image is transparent.
I've named the topper image so it will display properly with the table in PinballY menu.
The image displays as it should with the table, however, the transparent area of the PNG file is black, not transparent. I should be seeing bright red through the transparency.
This continues when the game is launched, I cannot see the topper video playing through the transparency, only black.
hope that helps...

**Comment by mjrgh** [comment]
Do you mean that you want the whole window to be transparent, so that another window **from another program** shows through?

**Comment by miguelcerca** [comment]
Correct

**Comment by mjrgh** [comment]
I'm afraid that's not possible.  Using a PNG with transparency as a background will only draw the transparent parts against the background of the window, which is opaque black.  It's not feasible to make the windows themselves transparent.
