### ISSUE TITLE
joystick input

### ISSUE THREAD

**Issue by d8thstar** [mjrgh/PinballY#133]
hey guys,

tryig to assign next and previous to joystick left/right but they dont take.  the joystick buttons work great though.

**Comment by ForceConstant** [comment]
Sorry to hijack issue, but how did you even set the joystick buttons? I just installed PinballY, and see the button options, but don't see how to program the buttons?

**Comment by mjrgh** [comment]
Joystick axes can't be used as buttons, but you can now program this sort of behavior through Javascript, as of 1.1 Beta 2.  See the help under Javascript scripting > Worked Examples > Joystick Game Switcher for an example showing how to implement this.
