### ISSUE TITLE
Overlay

### ISSUE THREAD

**Issue by JeffD78** [mjrgh/PinballY#135]
Hi, I think it can be a cool feature to add overlay like pbx. Per game and per system. Thanks

**Comment by JeffD78** [comment]
I have done this but with the underlay option. I think an overlay for playfield and backglass can be a really cool feature 
![15887563328211785464161239355507](https://user-images.githubusercontent.com/63658977/81160559-7cc89380-8f8a-11ea-8d07-d83f9418f558.jpg)

**Comment by JeffD78** [comment]
![15887563727573570024837969677150](https://user-images.githubusercontent.com/63658977/81160593-8ce07300-8f8a-11ea-9d6e-880e72848829.jpg)

**Comment by mjrgh** [comment]
This should be doable with Javascript - see the Drawing Layers section in the help: 
 http://mjrnet.org/pinbally/Help/DrawingLayer.html.  If anyone wants to write up a demonstration, please submit it to https://github.com/pinbally, and/or I can add it as a Worked Example.
