### ISSUE TITLE
Minimized for vp9

### ISSUE THREAD

**Issue by cuclis** [mjrgh/PinballY#136]
**Is your feature request related to a problem? Please describe.**
The minimized option not hide the vp screen at load.

**Describe the solution you'd like**
Include in parameters.
-minimized /play .... (yes, - /)
Works for all vp9 (and only vp9)

**Comment by mjrgh** [comment]
That's a VP command line parameter you're talking about, right?  If so, then you want to report it to the VP guys - it has nothing to do with PinballY, as PinballY is just passing the command line you specify to VP.

**Comment by cuclis** [comment]
-minimized /play are the official parameters for all vp9 versions.
You can put it in the default settings for those systems, if you wants.

Only information, very good program.
