### ISSUE TITLE
Capture audio. Wasapi

### ISSUE THREAD

**Issue by cuclis** [mjrgh/PinballY#137]
**Is your feature request related to a problem? Please describe.**
Ffmpeg not save audio on digital outputs, only on outputs marked as stereo 2 channels.

**Describe the solution you'd like**
Using audacity, and selecting WASAPI intead of directsound, save audio even on hdmi output.

**Describe alternatives you've considered**
Maybe ffmpeg can use wasabi, or comment it in the help page as a option to try.

**Comment by mjrgh** [comment]
You might want to check with the ffmpeg developers about this.  ffmpeg is a separate project, so I really can't handle enhancement requests for it here.
