### ISSUE TITLE
Navigate from Z to A in one step

### ISSUE THREAD

**Issue by jueank** [mjrgh/PinballY#139]
When navigating through the list of tables with the magnasave buttons (switching the starting character of the tables names), PinballY treats numbers and special characters just like any other alphabetical character. To my knowledge, the number of tables beginning with a number or special character is quite low in comparison to the number of tables per alphabetical starting character.
That means, when switching from '2' to '3' the user usually skips only 1 or 2 tables (e.g. from '2in1 & '24' to '300').
Or in other words, when the user wants to go from 'Z' to 'A', he has to hit the magnasave button quite often, just to skip a handful of tables.
I think it would be reasonable when PinballY would instead skips all tables which are listed after 'z' and before 'a' with one click of a magnasave button. The few tables inbetween can easily be reached with the normal flipper buttons.

**Comment by mjrgh** [comment]
Implemented in 1.1 Beta 2, as a new option to control how non-alphabetic titles are treated during Next/Previous Page commands - see the Game Wheel options.
