### ISSUE TITLE
Adjustable 'speed' for scrolling

### ISSUE THREAD

**Issue by jueank** [mjrgh/PinballY#140]
When 'scrolling' through the list of tables by holding flipper buttons, PinballY scrolls through the tables quite quick. Too quick to really follow individual tables. Usually the user (or at least me) only realizes a fraction of a second later when he scrolled over a particular table and has to navigate back.
I tried first to control the scrolling speed by lowering the keyboard repeat rate in Windows. This works per se - PinballY scrolls slower through the tables, but also has downsides.
- Since it's a global setting, this also leads to slower behavior in other places. For example scrolling through menus in PinballY. But also when using a text editor and wanting to scroll there. Or any other application. This is annoying.
- PinballY seems to use a fixed timeout preventing to pull and display assets (bg & playfield images & videos) while scrolling. If the keyboard repeat rate is high enough, only the wheels are scrolled, but bg & playfield asset is only shown when scrolling has stopped. However - when the scrolling speed is lowered, at some point PinballY starts to pull assets while scrolling, which leads to stuttering and heavy fluctuations per scroll step.

It would be good, if scrolling speed is a controlled property of PinballY itself. A proposal could be a simple configuration in the UI to only process every second received keystroke (or third, fourth, ...)
Pulling assets should be prevented until flipper buttons are released also for slower scrolling speeds.

**Comment by mjrgh** [comment]
Implemented in 1.1 Beta 2.
