### ISSUE TITLE
Option to filter for tables with missing assets

### ISSUE THREAD

**Issue by jueank** [mjrgh/PinballY#141]
When taking care of the tables, it would be nice if PinballY allows to be filtered to tables which have missing assets. (Missing wheel, backglass image / video, etc.). There are ways like filter for added within a week, but this does not cover all cases.
'Show unconfigured Games' is good, but after entering the 'Game Details' it's not really finally configured, right? The user often only knows afterwards, what filename to use for the wheel image.
Tbh. i don't know if this could be done with some custom javascript code, but on the other hand it might be useful enough to have it in the standard.

**Comment by mjrgh** [comment]
I added a ready-to-use script that sets up a filter for games with missing media, here:

https://github.com/PinballY/PinballY-Addons-and-Examples/tree/main/MissingMediaFilter

**Comment by jueank** [comment]
Hey!
Many thanks for supporting this and also implementing the other 2 issues (#142 and #143)! I'll check it out soon! :)
