### ISSUE TITLE
Configurable encoding option for ffmpeg

### ISSUE THREAD

**Issue by jueank** [mjrgh/PinballY#142]
At the moment the video encoding option for the first pass of 2 pass encoding with x264 is hard coded to preset 'ultrafast'. If i'm not mistaken, a typical 1st pass encode of a full hd playfield is ~1GB in filesize (20 - 30 sec video). I played around a bit - setting the media folder to an external usb harddrive, but the transfer rate was not high enough to transfer 1GB within 20 sec.

According to this comparison of x264 presets: https://write.corbpie.com/ffmpeg-preset-comparison-x264-2019-encode-speed-and-file-size/ the encoding time of 'veryfast' (and 'superfast') is practically identical to 'ultrafast' and 'faster' and 'fast' only slightly slower. However, the filesize of 'veryfast' is tremendously lower (~40%) than 'ultrafast'. Other presets are similar.

Irrespective of my rather unusual case from above - trying out other encoding presets might be beneficial for other use-cases as well. Maybe for 4K captures? It would be nice if the x264 preset could be configured (ultrafast / superfast / veryfast). An optional property in settings.txt would be totally sufficient. Also treating this as a 'beta' feature which might be removed again in future.

**Comment by mjrgh** [comment]
Implemented in 1.1 Beta 3.
