### ISSUE TITLE
PinVol feature request: Hide from Task Switcher

### ISSUE THREAD

**Issue by jueank** [mjrgh/PinballY#144]
Sorry to misuse the PinballY project for this feature request.
I see PinVol - which btw. is just as great as PinballY (thanks a lot for the great work!) - very similar to PinAffinity. It just does its job silently in the background with little reason to access its window often (or in my case nearly never).
I would prefer to have PinVol sitting in the tray area (liek PinAffinity) and not be listed in the Applications shown in Task Switcher. When cycling through windows while administering tables you constantly have to skip it.

**Comment by euston-r** [comment]
I second this suggestion.

Also, you need to be able to define where the volume display is shown. My cabinet is rotated 90% - but PinVol is designed for 270% - so the volume (green overlay) is displayed at the TOP of the screen and upside down 

I'm not running PinVol anymore for this reason - and the fact it should be in the system tray

**Comment by mjrgh** [comment]
If you could re-open this over at the PinVol repos, that would make it easier to track properly.  I'm going to close this here since it's a different program.

https://github.com/mjrgh/PinVol
