### ISSUE TITLE
Add option to show Info Box in attract mode

### ISSUE THREAD

**Issue by AlexNRW** [mjrgh/PinballY#145]
In attract mode

The infobox does show up when manually changing a game in wheel view (flipper buttons) as expected

But NOT when:

- game is auto changed in attract mode
- after startup
- after returning from a game (e.g. VPX) back to the wheel view

**Comment by mjrgh** [comment]
It's actually not meant to show up when in attract mode, but it should be showing up in the other cases, and indeed does for me; I'm not sure how to go about reproducing it.

**Comment by AlexNRW** [comment]
You are right. With point 2 and 3 I was wrong.

Anyways, an option to enable "show info box also in attract mode" would be great.

Why?
When friends are around (Party situation, yes hard to think about it now), they mostly choose tables, I rate high. Now, they don't have that info in attract mode...

Why not?
Well: Why not?

Maybe this can be done by some custom script? I discussed and searched, but couldn't find a solution.

**Comment by mjrgh** [comment]
The Info Box is deliberately turned off in attract mode because most people want attract mode to be a screen saver, thus you don't want any static image features like that. But it could be made into an option.

**Comment by mjrgh** [comment]
Option added in 1.1 Beta 2.
