### ISSUE TITLE
Option for "disableTrueFullScreen" when recording media for VPX

### ISSUE THREAD

**Issue by AlexNRW** [mjrgh/PinballY#146]
Many people like me run VPX in disable true full screen mode. But PBY can only record playfield videos, if this is turned off. It is frustrating, that you always have to turn off true full screen in VPX video settings before you can record a playfield video. In a way this makes the comfort of recording one video right now - which is a big advantage of PBY - obsolete.

Solution:
An option for disabeling this when recording VPX table videos. It is easy, VPX exe must only be executed with the argument -DisableTrueFullSreen. This is only used for the next execution of VPX and does NOT change settings in VPX.

Alternatively this argument could be used without any option - means always. Because the true fullscreen mode is only important for performance when playing, it can be dieabled for just watching or recording videos without any disadvantages.

**Comment by AlexNRW** [comment]
I bump this. Because it simplifies a lot, when recording from VPX....

**Comment by mjrgh** [comment]
There's a worked example showing how to implement this:

http://mjrnet.org/pinscape/downloads/PinballY/Help/CaptureCommandLineChangeExample.html
