### ISSUE TITLE
GPU and Fans run full blast at default screen until closed

### ISSUE THREAD

**Issue by electricmessiah** [mjrgh/PinballY#147]
When I run this front-end, my Nvidia RTX 2060 goes nuts just sitting at the default screen with no tables loaded. Fans come on and stay full blast until it's closed. I know this is beta, but this makes it completely unusable for me.

**Comment by wolispace** [comment]
I noticed after closing a table and it was PinballY was in its idle state, the fans/cpu were going full blast too (RTX 2080)

However multiple games in and out and it has not done this again yet.... today.

I'll keep my eye on this and report back if it happens again.

**Comment by electricmessiah** [comment]
I monitored it in GPU-Z and the temps go into the high 70s and stay there. This never happens with PinballX, and doesn't even happen with GPU intensive games on my RTX 2060. Not sure what's going on, but something is amiss!

**Comment by mjrgh** [comment]
You might try the **Lock frame rate to monitor refresh rate** option under Audio/Video settings.  See the help for an explanation: http://mjrnet.org/pinbally/Help/AudioVideoOptions.html.

**Comment by mjrgh** [comment]
Closing on the assumption that it's the frame rate issue.
