### ISSUE TITLE
Media capture and display for desktop users

### ISSUE THREAD

**Issue by toccata10** [mjrgh/PinballY#15]
I'm exploring the "capture media". That's a very cool feature ! It seems to be tailored to cabinet users.
I'm a Desktop user. It would be great if there was an option to choose between portrait and landscape to:
1) capture images and videos (today, they are cropped)
2) display them (today: large black borders)
Thanks again for sharing your tool.
A few pictures (and video) to illustrate my request:
![capture-pinbally](https://user-images.githubusercontent.com/7478580/47427266-1c02ad00-d790-11e8-9bd6-2a14d0d3e5e4.png)
![white water williams 1993](https://user-images.githubusercontent.com/7478580/47427272-1f963400-d790-11e8-9620-cc2791b9b37b.png)
[White Water (Williams 1993).zip](https://github.com/mjrgh/PinballY/files/2510259/White.Water.Williams.1993.zip)

**Comment by toccata10** [comment]
An update on this: if I launch pinballY in full screen, then launch the media capture, then the picture and video are correct (not cropped).
For the still playfield: that's perfect. The pb is with the video display: it stays in 9:16 ratio.
So, this bug should probably be closed and a new one would concern correct video playback for desktop users.
![capture-image-ok](https://user-images.githubusercontent.com/7478580/51784272-65271c00-2146-11e9-9734-d1e41cc1b156.jpg)
![capture-video-pb](https://user-images.githubusercontent.com/7478580/51784273-65271c00-2146-11e9-8810-03181ac9486e.jpg)
And the video captured:
[Batman (Stern 2008).zip](https://github.com/mjrgh/PinballY/files/2798760/Batman.Stern.2008.zip)

**Comment by toccata10** [comment]
That's probably a good solution.

**Comment by mjrgh** [comment]
Beta 3 should work better for you.  It has two changes that should help.  First, by default, it now preserves the native aspect ratio of the video or background image, rather than always trying to force it into 9x16 portrait format.  Second, there's now an option (in the Audio/Video section of the settings) that lets you stretch the playfield background to match the window size, rather than trying to preserve the aspect ratio.  I think the default setting that preserves the aspect ratio will work for your situation just fine, but if not you can try the "stretch" mode.

**Comment by toccata10** [comment]
With pictures, the stretch option works great:
no stretch:
![picture-no-stretch](https://user-images.githubusercontent.com/7478580/52174060-d9893d00-278e-11e9-9527-469a63f82e1d.jpg)
stretch:
![picture-stretch](https://user-images.githubusercontent.com/7478580/52174058-d5f5b600-278e-11e9-94b4-60127d2ae4f1.jpg)

With videos, unfortunately, it doesn't stretch:
no-stretch:
![video-no-stretch](https://user-images.githubusercontent.com/7478580/52174070-eefe6700-278e-11e9-9404-846ac9ffd55d.jpg)
stretch:
![video-stretch](https://user-images.githubusercontent.com/7478580/52174075-f887cf00-278e-11e9-93a8-efdec86b2968.jpg)

The video file recorded with the pinbally capture:
[Red & Ted's Road Show (Williams 1994).zip](https://github.com/mjrgh/PinballY/files/2825289/Red.Ted.s.Road.Show.Williams.1994.zip)

**Comment by mjrgh** [comment]
You're quite right...  I didn't test it thoroughly enough with source material with different aspect ratios.  I've fixed it for the next update (and hopefully I got it right this time).

**Comment by mjrgh** [comment]
Just released Beta 4 with the fix.  Give it a try and let me know if it works better for you.

**Comment by toccata10** [comment]
It works perfectly now. So cool to be able to batch capture the videos from my tables. Thanks so much !

**Comment by mjrgh** [comment]
Glad to hear it!
