### ISSUE TITLE
A-Z keypress to jump to that letter table

### ISSUE THREAD

**Issue by wolispace** [mjrgh/PinballY#150]
I know we have key assignment limits so this is possibly impossible but it would be great to navigate quickly to a table using keyboard shortcuts eg hit W and we are at Warlok, then hit G and we are at Gene etc..

Or maybe just two keys, each press goes either up or down one letter.

**Comment by miguelcerca** [comment]
Left and right magna save (control keys) jump one letter already...

**Comment by wolispace** [comment]
Ah.. Great didn't know that.
