### ISSUE TITLE
Hide known files

### ISSUE THREAD

**Issue by wolispace** [mjrgh/PinballY#151]
Really small trivial suggestion.. I see a file called game_cfg showing as a table.

Investigate and I see its game_cfg.pxp, so its from the FX3 table folder - but from the looks of it its not actually a table (but who knows with some FX3 tables) 

Can this be be added to a black list you use to exclude non-table files?

I'm also seeing files like

- gui
- gui_cfg
- cui_sfx
- preview
- PTSData
- sfx
- txt
- V12 (mind you this really could be a table :-)

**Comment by stephenhouser** [comment]
V12 is a table. Think V12 engine on a car.
I just configured the dummy tables (gui, gui_cfg, etc.) and then hid them using "hide table" as a workaround to the non-tables.

**Comment by mjrgh** [comment]
Hmm, this doesn't seem like something I'd want to add as a built-in feature - it's too FX3-specific, and it would require some kind of Yet Another Config File, or at least some config information somewhere to hold the black-list.  I don't want things to go in the direction of Linux software with boundless proliferation of hidden .config files.

Maybe someone could write this up as a Javascript add-on, and contribute it to https://github.com/PinballY/PinballY-Addons-and-Examples?  I think an approach that would work there would be to scan the master game list (via [gameList.getAllGames](http://mjrnet.org/pinscape/downloads/PinballY/Help/GameList.html#getAllGames)) at startup, cross-reference it against the black-list (which could just be incorporated in the Javascript code directly, to keep everything self-contained), and set each matching game's isHidden property to true (via [GameInfo.update](http://mjrnet.org/pinscape/downloads/PinballY/Help/GameInfo.html#update).
