### ISSUE TITLE
Double logo showing after choosing table

### ISSUE THREAD

**Issue by githubmarie** [mjrgh/PinballY#152]
When I choose to start a table a second table logo appears just above the table logo that is highlighted in the wheel.

Also when the table ends this same behaviour is noticable. Aftter the table fully stops the second logo also disappears again and I can scroll in the wheel.

As a picture says more than words: [https://ibb.co/vPnJMRY](url)

I have: latest Pinbally 64 bit (I didn't have this with 32 bit) W7 64 Dutch

tried: Under Restore full-screen windows based on:, select Exact saved pixel coordinates
but no result.

**Comment by mjrgh** [comment]
The image seems to be missing.

Are you using any Javascript add-ons?  It sounds like you're probably hiding the normal black background that appears during game loading.

**Comment by mjrgh** [comment]
This isn't reproducible, so I'm going to assume you're doing something with Javascript that's causing it.  You should be able to fix it at the script level.

**Comment by githubmarie** [comment]
Just saw your messages. If it is useful, please see the screenshot. I am not having any programming skills, so not using javascript. Yes I was hiding the black picture. Trying to achieve: if you merely want to keep the game's background video or image showing during launch, for a "seamless" launch effect, all you have to do is provide a transparent PNG file for the launch background.  For your convenience, a suitable file called "Transparent.png" is included in the Media file.  Simply copy this file into the Media > Images folder and rename it to "Game Launch Background.png"
[
![gnr](https://user-images.githubusercontent.com/47717624/116605906-4c62cd80-a930-11eb-8154-17bcbb04545f.jpg)
](url)

**Comment by mjrgh** [comment]
The transparent PNG would definitely be the problem - that's leaving the full normal display intact, including the wheel icon, so what you're seeing is the wheel icon for the launch superimposed over the normal screen.  You can fix this easily by using the techniques in the Seamless Launch example in the help:

http://mjrnet.org/pinscape/downloads/PinballY/Help/SeamlessLoadingExample.html

**Comment by githubmarie** [comment]
Will look into that and try. Thanks!
