### ISSUE TITLE
Zaccaria tables - solution

### ISSUE THREAD

**Issue by euston-r** [mjrgh/PinballY#153]
I got Zaccaria tables working properly lasty night - so I thought I'd share here, and maybe they can be added as a "recipe" - or a pinbally provided system

Zaccaria uses a setup.xml to work out your last table, so the hack to get this working is to a) use an AHK script to edit the settings.xml file, then b) use scripted keystrokes to get to the desired table on startup

This is normally done in the one ahk - but pinbally wont allow for this, as the keystrokes dont work from the AHK. So my solution is use the "run before" option, passing the table name to  a COMPILED ahk which does the edit, then Pinbally starts Zaccaria and does the key presses :

Here;s my settings for Zaccaria 👍 

`System Class : STEAM

Program EXE : [STEAM]

Parameters: -applaunch 444930 -rotate left

Startup Keys : [pace 1000] [click playfield] enter enter enter enter [pace 2000] enter enter [pace 1200] enter enter

Run before : c:\Zaccaria\LaunchZaccaria.exe [[TABLEFILE]]
`
What follows is the code for LaunchZaccaria.ahk - which needs to be compiled. - Not my code, but I hacked it for PinballY :)

[LaunchZaccaria.zip](https://github.com/mjrgh/PinballY/files/4936850/LaunchZaccaria.zip)

**Comment by euston-r** [comment]
Yeah I know, my startup key string is a mess - I'm sure someone else can clean it up - but it works.

Forgot to mention that this method requires a PinballX style Zaccaria.xml - see AHK code

**Comment by mjrgh** [comment]
I think an improvement would be to get rid of the AHK script and do this from Javascript in PinballY.  It would be a lot more self-contained that way.  You can set up a **prelaunch** event handler that does file editing.  See Javascript scripting > Events > Event Types > LaunchEvent in the help for **prelaunch** details, and see Javascript scripting > OLE Automation for an example of accessing files using the OLE Scripting.FileSystemObject.

**Comment by mjrgh** [comment]
The AHK script looks pretty complex, so I'll just leave it at that and add this as a recipe to the help.  Thanks for providing it!
