### ISSUE TITLE
Visual Pinball X not focused

### ISSUE THREAD

**Issue by beneva52** [mjrgh/PinballY#155]
When I launch tables with BG and UltraDMD, I often cannot play because the "Visual Pinball Player" is not activated.
I have to get my keyboard out and Alt-Tab or click with my mouse to give it focus.

Could you help me please?

**Comment by mjrgh** [comment]
You might want to try experimenting with using the Startup Keys option to send a mouse click automatically, using the [click playfield] sequence.  See http://mjrnet.org/pinbally/Help/SystemOptions.html, and scroll down to "Startup Keys".  If that doesn't fix it reliably by itself, try adding a short pause before the click with [pause 123] (replacing 123 with the pause interval you want to use, in milliseconds).

**Comment by beneva52** [comment]
Thanks for your answer, I had already figured out the "click playfield" trick and it worked perfectly.

**Comment by BluetriX** [comment]
Hi - I have this same issue. I tried:

Startup keys: 
[pace 5000] [click playfield]
[pace 15000] [click playfield]
[pace 20000] [click playfield]
[pause 20000] [click playfield]
[pause 20000] [click playfield] [click playfield]

but the focus is never right. In some cases a menu opens and asks if I want to resume. Then I can click resume and then the focus is ok.

I am using VPX8. It starts in Exclusive Fullscreen Mode. How can I fix this?
