### ISSUE TITLE
Select category filters by button presses

### ISSUE THREAD

**Issue by Anjiro76** [mjrgh/PinballY#158]
Hi, i'm using Pinball Y as i think it'is the best around and surely dumb proof front end :D (as positive thing!!!!)
 it's so easy to manage media... i'd say in real time, i add media ? i can see it right away !
 but one option i think is missing, it's a real important option (my thought)
 we really need to select categeories with 2 simple keys:
 
 previous cat, next cat 
(maybe we can assign those keys to magnasave buttons ;) )

"ALL tables" category is mandatory too =P

 it'll be really usefull to select a categ like this instead of entering a menu (1) go down to Categories... select 
 categ filter... and finally the categ we like...
 
 hope u'll mind about this..
 
 Thank you in advance 
 
 Angelo

**Comment by mjrgh** [comment]
I'd suggest using Javascript for this.  Take a look at these sections in the help for pointers:

Javascript Scripting > Worked Examples > Custom Button Command - shows how to assign buttons to custom scripts
Javascript Scripting > Worked Examples > A "Top 10 Filter" - to get an idea of how to invoke filters in general
Javascript scripting > System Classes > FilterInfo - details on js access to filters
PinballY Help > Javascript scripting > System Objects > gameList - details on js access to the game list

Here's an outline of how you could approach this:

1. Set up some custom button commands for "Next Category" and "Previous Category", as described in the Custom Button Command section 
2. Assign those commands to the key inputs of your choice, which you proposed for the MagnaSave buttons
3. In your Next and Previous Category handlers, use gameList.getAllFilters() to get a list of all of the filters, and select the subset with ID values starting with "Category." (see "Filter IDs" in the FilterInfo section listed above)
4. Use gameList.getCurFilter() to get the current filter, find it in the list of all category filters, and use it to decide which category filter to navigate to next.  If the current filter is a category filter, you'd simply use the next/previous in the list. If the current filter isn't a category filter, you'd probably navigate to the first/last category filter, although maybe you'd find some other behavior more pleasing, such as "ignore the button entirely in this case" or "select the All Games filter".  Experiment and see what you prefer.  That's a nice thing about doing this with Javascript, - you're not stuck with whatever policy seemed best to me.

This would make a good worked example!  If you want to develop the javascript, I'd be happy to add it to the worked example section.  If you're not interested in doing the work, I'll at least keep it in mind as a worked example to visit in the future.

**Comment by Anjiro76** [comment]
Hi and thank you for the reply.
I'm less than a noob when it comes to java XD ... but i'll follow ur directions and will make some researches..
meanwhile ... i managed to make a script with AHK (i'm a noob here too :V) 
let's say i have 5 categories.... i can select "next" one with a single button click... when the selection is the last
category in list... it'lll start from category 1 again on next ""next categ".
As it works perfectly.. it's not rly ""good to look at" as we can see the RLY FAST "entering menu, option selection, category selection" ... will do for now XD
let's study some java XD

thank you!

**Comment by mjrgh** [comment]
I added a ready-to-use script implementing simple category navigation by buttons, here:

https://github.com/PinballY/PinballY-Addons-and-Examples/tree/main/CategoryButtons
