### ISSUE TITLE
Add command line options to start game, capture media

### ISSUE THREAD

**Issue by xantari** [mjrgh/PinballY#159]
It would be nice if you could issue the following command line options to PinballY:

1. Start a table. Such as PinballY.exe -StartGame "game name"
2. Begin a table record such as PinballY.exe -RecordGame "GameName"

Reason being is so that I can piggy back off of those features for the game manager i'm working on that I hope to make compatible with PinballY:

https://github.com/xantari/PinCab.Configurator

**Comment by mjrgh** [comment]
I suspect this will be a bit of a pain to implement, and it seems pretty specific to your use case, so I'm probably not going to be able to get to it any time soon.  I'd be happy to consider a pull request, though.

**Comment by xantari** [comment]
I'm going to close this. Planning on a different implementation plan for the tool i'm working on.

I just haven't had a whole lot of free time to finish it up.

The plan is to use OBS exclusively for all video recording, and likely setup a websocket connection to the running instances to control them (or just end the OBS recording processes, but need to test if that will work).

FFMpeg has issues with exclusive full screen programs, and OBS seems way more capable in that regard, and has options for built in AMD and NVidia GPU encoding and a bunch of other more advanced recording features that FFMpeg can't match.

About as far as I got is the screen:

![image](https://user-images.githubusercontent.com/6610039/116479724-bd798680-a845-11eb-80a6-3e2e75c03313.png)

None of the front end's do recording particular well. I've historically had problems with Pinball X, Pinball Y only has options for FFMpeg so I believe there are issues with exclusive full screen programs like future pinball, and pinup popper's recording function is a mess, it's a series of .bat files, AHK scripts, and is just not super user friendly in my opinion. Also it's not open source.
