### ISSUE TITLE
Stereo mix not enabled/found

### ISSUE THREAD

**Issue by RoelHermus** [mjrgh/PinballY#16]
Hi, I am using a couple of days your beta 64 bit version on windows 10 release 1803. When I try to capture a video with audio I get a message Audio capture unavailable. First, there was no stereo mixer. I get the driver from Realtek and the stereo mixer is there. But its still inpossible to capture a video with audio. Only video works fine. I try lots of things without results. But, I found on internet that there is no support for the stereo mixers in release 1803. Is that maybe the issue? Btw, recording some music with a recording app works fine.

Another point is that sometimes the backglass picture is frozen after playing a pinball game or when I close the game menu.  Sometimes I can unlock it with the esc button. Sometimes I must start PinballY again.

After all, I more then happy with your PinballY. I love it very much! Thanks so far.

**Comment by mjrgh** [comment]
Great!  

It must be a slight difference in the naming for the version you're using.  The names doesn't have to be "Stereo Mix" exactly, but it has to **contain** the string "Stereo Mix".  The hyphen in your version must have thrown it off.  I'll plan on making a couple of a couple of things to make this more flexible:

1.  Make the string match more flexible, so that it matches "Stereo-Mix" as well as "Stereo Mix".  Maybe look for a wildcard pattern like "Stereo<anything in the middle>Mix".

2.  Add a way to list the available devices and manually select one, if a match for "Stereo*Mix" can't be found, just in case there are even more variations on the name out there (there probably are!).

**Comment by RoelHermus** [comment]
Yesterday it was the first time I used FFMPEG. I know not so much of it, but found the "show device list" option and found out that it matched with the "Friendly Name"in the register.The next stap was simple. I changed the reg-key and go. Problem fix.

But I'm not sure of the "Fiendly Name" in different languages use "stereo" and "mix" in it. Checking only on that two words is maybe not the best solution. In dutch (my language) is it almost the same as in English.

 Your option 2 looks the best one. But next problem is when users select the wrong one, the audio is not captured. Up to you to find the best solution.

**Comment by toccata10** [comment]
On a french version of win10: see the problematic name. So audio recording is not working by default for me.
```
c:\Visual_Pinball\PinballY\ffmpeg64> ffmpeg -list_devices true -f dshow -i dummy
ffmpeg version 4.0.2 Copyright (c) 2000-2018 the FFmpeg developers
  built with gcc 7.3.1 (GCC) 20180722
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-bzlib --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth
  libavutil      56. 14.100 / 56. 14.100
  libavcodec     58. 18.100 / 58. 18.100
  libavformat    58. 12.100 / 58. 12.100
  libavdevice    58.  3.100 / 58.  3.100
  libavfilter     7. 16.100 /  7. 16.100
  libswscale      5.  1.100 /  5.  1.100
  libswresample   3.  1.100 /  3.  1.100
  libpostproc    55.  1.100 / 55.  1.100
[dshow @ 0000022bdf24a280] DirectShow video devices (some may be both video and audio devices)
[dshow @ 0000022bdf24a280] Could not enumerate video devices (or none found).
[dshow @ 0000022bdf24a280] DirectShow audio devices
[dshow @ 0000022bdf24a280]  "Mixage st├®r├®o (Realtek High Definition Audio)"
[dshow @ 0000022bdf24a280]     Alternative name "@device_cm_{33D9A762-90C8-11D0-BD43-00A0C911CE86}\wave_{9B93C9FB-767E-4C14-9C14-9BC311BBACD8}"
[dshow @ 0000022bdf24a280]  "Microphone sur casque (Wireless Controller)"
[dshow @ 0000022bdf24a280]     Alternative name "@device_cm_{33D9A762-90C8-11D0-BD43-00A0C911CE86}\wave_{1D0BB9FE-E3FB-4773-A7F3-13134C5BA18E}"
```

**Comment by mjrgh** [comment]
For the next update, I've added an option to the settings dialog that lets you select the exact device you'd like to use.   The default is still to search for something with "Stereo Mix" in its name, but the new setting will let you override that on your machine for whatever the local name is.

**Comment by mjrgh** [comment]
Should be fixed now in the Beta 2 release.
