### ISSUE TITLE
Documentation (Help) does not list media file types that are searched for in media directories

### ISSUE THREAD

**Issue by stephenhouser** [mjrgh/PinballY#163]
The current documentation lists some file types that are searched for but not all. I cannot find where the documentation is built from so am putting this issue here.

Example, from the `DirectoryInfo.html` 
```
The extensions (.ext) are the usual set of supported format extensions for images and video files: .png, .jpg, .mp4, etc.
```
Which leaves the user to wonder, "will my .mov file work?"

**To Reproduce**
This is missing documentation 

**Expected behavior**
The documentation should list:
* Searched video extensions: .mp4, .mpg, .f4v, .mkv, .wmv, .m4v, .avi
* Searched Image extensions: .png, .jpg, .jpeg, .gif

**Comment by stephenhouser** [comment]
Doh. There's the documentation right there in `Help`.

**Comment by mjrgh** [comment]
I added a list to the documentation in 1.1 - under the Files & Folders section:

http://mjrnet.org/pinscape/downloads/PinballY/Help/DirectoryInfo.html

("Supported media file formats and extensions")
