### ISSUE TITLE
Pinball fx3 doesn't save high scores when PinballY terminates it via Close Window

### ISSUE THREAD

**Issue by redmagic** [mjrgh/PinballY#167]
Hi, it seems exiting fx3 through pinbally’s alt f4 method prevents highscores from being saved. Is any one experiencing this or knows a fix?

Thanks!

**Comment by mjrgh** [comment]
If you were running FX3 standalone, how would you normally exit the program?  Is there a keyboard sequence or mouse selection you'd normally make?  Maybe I could add a way to simulate whatever that is, as a new Terminate By option.

**Comment by redmagic** [comment]
Hi, thanks for responding. I do not think this isssue is PinballY related. After some more observation, I think that scores are saved separately for single player and hotseat games. Thanks for making PinballY, it is working nicely for me.
