### ISSUE TITLE
Category Manager

### ISSUE THREAD

**Issue by worksasdesigned** [mjrgh/PinballY#168]
A Category Manager is missing.
Right now i have around 80 FX3 and 170 VPX Tables + some other stream Games.

My categories are like:
- kids tables
- hard table
- fun tables
- must play
- action shooter
- ....

If i want to organize my tables with tags/categories its a lot of work to 
- search the table
- push button for menu
- go down 3 steps for operator menu
- open game setup
- go down 3 steps for openening 
- go down x steps to select category
- go down x steps to save
- confirm save

Optimal solution would be:
- select a category 
- show a list with all tables
- mark the tables which should get the tag
- save entire list

This can be a windows styled option list as the Game details.

**Comment by mjrgh** [comment]
This sounds like a good Javascript add-on.  You might go over to https://github.com/pinbally and see if anyone there is up for implementing it.  (Or if you want to give it a shot, that would be a good place to share it.)

**Comment by mjrgh** [comment]
Here's a Javascript add-in that should do the trick:

https://github.com/PinballY/PinballY-Addons-and-Examples/tree/main/BatchCategoryTagging

**Comment by worksasdesigned** [comment]
Thank you!
