### ISSUE TITLE
Have you tried swf2js?

### ISSUE THREAD

**Issue by mase76** [mjrgh/PinballY#169]
Hi!
Have you tried swf2js to convert the swf instruction cards?
https://github.com/swf2js/swf2js

**Comment by mjrgh** [comment]
That looks interesting, but unfortunately it's browser-based, so I'm not sure what we could do with it here.  If you find something like that as a C++ library, that's something I could add to PBY.  Or if you find a standalone tool that can do bulk file conversions, that's something I could at least point people to, to convert their collections.

**Comment by mase76** [comment]
Some of the swf files can be disassembled with flasm and played with a mplayer or similar.
https://sourceforge.net/projects/flasm/

**Comment by mjrgh** [comment]
> Some of the swf files can be disassembled with flasm and played with a mplayer or similar.

I'm not sure how that would apply here... do you have a usage procedure in mind?

**Comment by mase76** [comment]
Just disassemble the swf with flasm and play it with a mediaplayer. However it does not work with all kind of files, but this would be a beginning. It is a command line tool, so you could disassemble it to a temp directory, and embed a mplayer view to show the instructioncard.
On the other side, what is wrong  to use swf2js and create a webview for the instruction card.
These were the only 2 ways I could find so far, and I wanted to point you on them.

**Comment by mjrgh** [comment]
> Just disassemble the swf with flasm and play it with a mediaplayer

Great, but again, how does this work with PinballY?

> On the other side, what is wrong to use swf2js and create a webview for the instruction card.

Nothing wrong at all!  But same question: what do you do with that in PinballY?

**Comment by mase76** [comment]
How are the files played, when the flash plugin is installed? Isn't it a webview, too?
When you can make the files playable with a mediaplayer, there are all kind of libs to use in your application.
I think, there are only 2 ways to play them. A webview or a mediaplayer. Maybe an image view for non animated ones.
What format do you expect for a direct playback in PBY?

**Comment by mjrgh** [comment]
> How are the files played, when the flash plugin is installed? Isn't it a webview, too?

No, it's an embedded Flash object.

> What format do you expect for a direct playback in PBY?

See the list of supported formats:  http://mjrnet.org/pinscape/downloads/PinballY/Help/DirectoryInfo.html
