### ISSUE TITLE
Portrait Mode Video Problems

### ISSUE THREAD

**Issue by dcbenji** [mjrgh/PinballY#170]
Videos captured at 1440x2560 in portrait mode with either OBS or nvidia shadow play are played back sideways/rotated and stretched by PinballY. I've tried captureing at 1440x2560 and outputting at 2560x1440 to see if PinballY would stretch it 'back to normal' but this doesn't seem to work either.

**Comment by mjrgh** [comment]
You're talking about capturing with third-party tools, not with PinballY?  In that case, yes, you'll have to tell the capture tool to rotate the videos, or rotate them after the fact using a second tool (ffmpeg can do this).  Table images and videos need to be oriented with the bottom of the playfield facing the left side of the screen:

![image](https://user-images.githubusercontent.com/8271213/116462469-5694a700-a81e-11eb-826b-69d945953d14.png)
