### ISSUE TITLE
Support AlternateExe tag from PinballX

### ISSUE THREAD

**Issue by xantari** [mjrgh/PinballY#171]
**Is your feature request related to a problem? Please describe.**
PinballX had the ability to define AlternateExe tags in the database XML file so you could define a single system "Visual Pinball" and it would dynamically change to launch the correct .exe.

This will allow the Visual Pinball X system registration for example to automatically switch between the more stable VPinballX.exe and say perhaps VPinball10.7Beta.exe.

**Describe the solution you'd like**
Support the alternateexe tag that is capable in PinballX. Here is an example of a game in the Visual Pinball X system that has a few 10.7 only tables spread throughout the regular 10.6 tables.

```
 <game name="007 Goldeneye (Sega 1996)">
<description>007 Goldeneye (Sega 1996)</description>
<rom></rom>
<manufacturer>Sega</manufacturer>
<year>1996</year>
<type>SS</type>
<hidedmd>True</hidedmd>
<hidetopper>True</hidetopper>
<hidebackglass>True</hidebackglass>
<enabled>True</enabled>
<rating>0</rating>
<alternateexe>VPinball10.7Beta.exe</alternateexe>
```

**Describe alternatives you've considered**
Not sure the best solution to this when you don't want to transition all your tables to an unstable version of Visual Pinball other then to create another system registration, but then I think you have to split up your tables in new folders, then there's questions on if you then have to clone screenres.txt as well which is typically in the Tables folder.

**Comment by mjrgh** [comment]
I'm not sure if you're aware, but PinballY lets you set up any number of systems that share a Tables folder.  You can then switch individual games from one system to another that shares the folder using the System drop-list in the Edit Game Details box.  No need to edit the XML.

**Comment by xantari** [comment]
Gotcha, closing
