### ISSUE TITLE
Menu-Sound in table while holding a flipper button

### ISSUE THREAD

**Issue by worksasdesigned** [mjrgh/PinballY#172]
**If this is your first bug report**
Please read [How to write a good bug report](https://github.com/mjrgh/PinballY/wiki/How-to-write-a-good-bug-report)

**Describe the bug**
I have upgraded vom 1.00 to latest version 1.1 beta 2
If i'm in a table playing and holding a flipper button for longer than 1 second a sound gets played. It sounds like the menu-item-switch sound. 1 sound - little break - than machine gun like. Same behavior as if you hold a flipper button if you are in any pinbally menu.

Sound reacts to "Mute Button sounds when auto repeating" Option. So it must be a menu cyceling in the background.

**To Reproduce**
Play a table - hold left flipper button for > 2 seconds.

I have cross checked with backuped version of 1.0.0 - bug doesn't exist there.

**Windows version**
Win 10

**Additional context**

**Comment by mjrgh** [comment]
Fixed in 1.1 Beta 3.
