### ISSUE TITLE
PinballY stop responding when certain audio enhancer software is runnnig.

### ISSUE THREAD

**Issue by fernandojconti** [mjrgh/PinballY#178]
PinballY stop responding when certain audio enhancer software is runnnig.

Tested on Win10 x64, PinballY version 1.0.0 build 9375 (x64, 20200723-1914) and PinballY version 1.1.0 (Beta 5) build 9931 (x64, 20210518-0551)

If a program called FxSound is installed, active and working on the system, every time PinballY starts automatically when the operating system starts, it hangs after the interface loads and any cabinet button is pressed.

Steps to reproduce it:

1. Goto https://www.fxsound.com/plans and download the software called FxSound free  ( https://downloads3.fxsound.com/fxsound/2/fxsound_setup.exe )
2. Microsoft Visual C ++ 2015-2019 x64 redistributable is downloaded and installed automatically if necessary when setup is started.
3. Wait until the software is installed and launched (restart maybe will be necessary)
4.  Once the software is installed and launched, click on on "Get started for free"
5. Be sure the big "Power on" button is on red color meaning the software is active.
6. Click on the upper right X to close the window
7. Be sure that PinballY is configured to start up automatically every time Windows startup going to Options > Startup > How to start PinballY : and select "Automatically: ..."
8. Shutdown the system by PinballY
9. Startup the system and wait for PinballY to load.
10. Press a flipper button trying to browse the table collection.

Expected
PinballY should browse the tables collection normally.

Actual
PinballY hung up and stopped responding after pressing any button on the cabinet and a window appears offering to wait or close the application. If the user chooses to close the software and restart PinballY again, this time it will work normally.

**Comment by mjrgh** [comment]
Given that it works if you reload PinballY, you might try setting a delay in the PinballY auto-launch, long enough to make sure it launches after the other program.  It's probably some kind of interaction with focus or something like that; maybe changing the launch order will fix it for you.

**Comment by fernandojconti** [comment]
Delaying the PinballY auto-launch didn't work but it did with the other program. I used a separate software to manage the auto start programs that have an option to configure a delay time and that resolved the issue.
