### ISSUE TITLE
Importing custom table images

### ISSUE THREAD

**Issue by mase76** [mjrgh/PinballY#180]
Hi!
To import custom images I always have to open the windows filemanager. Can you add a filepicker to the game setup? How about importing instruction cards?

**Comment by mjrgh** [comment]
I'm not sure what you're asking that you can't already do.  You've read through the Help under **New Table Setup** (specifically, look at "Step four: download media", particularly the last paragraph) and **Files & Folders**, right?  If those don't point you in the right direction, could you be more specific about what you're trying to do?

**Comment by mjrgh** [comment]
Oh, I see you rewrote the request to talk about a "file picker".  The drag-and-drop approach doesn't work for you?

**Comment by mjrgh** [comment]
Also, if you have some particular repetitive workflow that you want to simplify, you might be better off looking at a Javascript solution.  It's easy to move and copy files in Javascript using the Windows standard Scripting.FileSystemObject, and it's easy to get the media file locations for a particular game (under the help, see **Javascript scripting > System Classes > GameInfo**, particularly resolveMedia()); combining those two, you could set up a command that moves all of the media files for a game from a source location you define to the correct PinballY media folder, without having to manually pick files.

**Comment by mase76** [comment]
For drag and drop I have to use a keyboard and mouse and have to overlay the windows explorer. But I can deal with it. I did not get it for wheel images, flyers and instruction cards. I would suggest to support hyperpin media packs for import. That would solve most of that issues.

**Comment by mjrgh** [comment]
HyperPin media packs are supported - just drop one on the main window.

**Comment by mase76** [comment]
Really? Did I miss some instructions?
I think, then we can close this issue.
