### ISSUE TITLE
Spacebar startup key

### ISSUE THREAD

**Issue by joshtynjala** [mjrgh/PinballY#201]
**Is your feature request related to a problem? Please describe.**

I’ve added a Steam game (Demon’s Tilt) as a custom system, and I want to specify some startup keys when it launches so that I can get through the menu. The GUI buttons are triggered by keyboard using the spacebar only, instead of the typical enter/return. 

**Describe the solution you'd like**

Please add support for spacebar as a startup key. 

**Describe alternatives you've considered**

i have tried many keys to trigger these buttons, but only spacebar seems to work.

**Additional context**

**Comment by mjrgh** [comment]
You actually can send a space key - the keyword is "space".  (I see that I missed that one in the documentation, but it's there in the program.)

**Comment by joshtynjala** [comment]
@mjrgh Thanks!

**Comment by mjrgh** [comment]
Added to documentation in 1.1.0 Beta 6.
