### ISSUE TITLE
DMD (3rd Monitor) focus

### ISSUE THREAD

**Issue by steveg64** [mjrgh/PinballY#21]
Hi MJR,
 
Maybe this is just a problem with my setup but when lunching from PinballY (or capturing media) a table that incorporates the DMD with the Blackglass (B2S DMD), the focus goes to the real DMD instead.
If I run direct from VP or from PinballX the focus is on the B2S DMD.

First picture as it should look, lunch directly with VP:
![dmd 1](https://user-images.githubusercontent.com/45360361/49017004-9f446380-f17f-11e8-9330-edd60aa282ae.jpg)

Second picture lunching through PinballY to play or capture media:
![dmd 2](https://user-images.githubusercontent.com/45360361/49017135-fba78300-f17f-11e8-85c9-ba45bf87c6e7.jpg)

**Comment by mjrgh** [comment]
I'm not sure what's going on there.  PinballY mostly just leaves it to the launched game to work out initial focus and window layering.  With the combination of VP + B2S + real DMD, you have three separate subsystems fighting over the initial focus and foreground layer, and a lot of how that works out comes down to the order in which the windows open.  The only involvement PinballY has in that process is setting the launched process's window mode.  So you might try changing the initial window mode for the version of VP you're using in the Settings dialog.  The setting for VP that works best for most people is "Minimize (SW_SHOWMINIMIZED)".

**Comment by steveg64** [comment]
All working now - thanks!

Best Regards
Steve...
 
14 Wheat Close
Chandlers Ford
Hampshire SO53 4HA

Mobile Phone: +44 7827 959779
Skype: seg0205

**Comment by mjrgh** [comment]
Great!
