### ISSUE TITLE
Is Pinball Y maintained anymore?

### ISSUE THREAD

**Issue by jaoxford** [mjrgh/PinballY#236]
Just curious if this is maintained anymore? Last commit was a few years ago, multiple pull requests, and issues. Seems a shame since this is a great bit of kit.

Does anybody have any suggestions on what the alternatives can be? I know of Pinup popper, that's not open source which is a bit of a disappointment. I suppose we could take over from the author of this project or create a fork and point everybody to that!

**Comment by mjrgh** [comment]
Yes, I still consider it an active project, although I also consider it more or less complete for the time being.  If there are open bugs that are getting in the way for your use, feel free to add comments on them to that effect - that could help in prioritizing work if I turn my attention back to it at some point.  And of course, as you say, it's an open source project, so also feel free to take the initiative on fixing any issues that are blocking you or adding any features that are critical to you.  Pull requests are appreciated for anything you fix/add.

**Comment by jaoxford** [comment]
Great, thanks for your response!
