### ISSUE TITLE
PinballY doesn't understand instruction cards

### ISSUE THREAD

**Issue by maperks** [mjrgh/PinballY#25]
Certain things from downloaded ZIP files like flyer images and instruction cards are not loaded. Therefore not surprisingly I couldn't find a way to display instructions.

**Comment by mjrgh** [comment]
Could you be more specific?

**Comment by maperks** [comment]
I have a HyperPIn ZIP file for AC/DC where the wheel image and some instruction SWFs are provided. Only the wheel image got loaded. Looking at the file more closely it looks like it has the instruction cards in the wrong directory. I now tried a different file and it is fine.
