### ISSUE TITLE
Can't find new tables to be configured (external system)

### ISSUE THREAD

**Issue by dch850** [mjrgh/PinballY#29]
I can't succed to add new table with  a new system (I wanted to launch pro pinball ultra from pinballY). 

I configured it but new tables to be configured did not come, I put a fake extension in the "file extension" and put a fake file (as it's not really tables files to be used), but the new tables never came in the list of unconfigured tables.

I finally manage to do it while using the "future pinball" system (as I'm not using future pinball at all so ti was free to be used), put a fake timeshock.fpt file in the table folder and then the table came in the list of table to be configured.

**Comment by mjrgh** [comment]
You have the right idea with the fake table files - automatic table discovery is based on files in the file system, so if you want the system to discover files that way, you have to create something for it to find, even if they're not actually going to be used by the game player system itself.

When you set up the new system, did you set the Table Folder properly?  That's where it's going to look for your fake files.  If it didn't find your files, my guess is that you didn't set the Table Folder path for the system, or that you didn't put the files in that folder.

**Comment by dch850** [comment]
I've double checked and the folder path is OK, I've retryed with various folder path and/or extension, but nothing to do, the new tables never comes.

You confirm that if the folder path is well configured and if a file with the extension specified is in this folder, the file should come in the table list ? nothing else to do ?

is there any restrictions regarding the folder path or the extension to be used ? Do you see any other reason for why it's not working ?

If I'm the only one having this, for sure the issue is between the screen and the chair but can't see what I'm doing wrong...

**Comment by mjrgh** [comment]
> You confirm that if the folder path is well configured and if a file 
> with the extension specified is in this folder, the file should come 
> in the table list ? nothing else to do ?

Right, you're definitely doing the right things there.

It might help to enable logging for table searches and then look at the log file.  Bring up the settings dialog, go to the Log File section, and make sure that "Player system setup and table searches" is checked.  Save changes if necessary.  Exit out of the program, then do a fresh run - launch PinballY, let it finish starting up, then quit out of it.  Now look at PinballY.log (it'll be in the same folder as the PinballY executables).  It should give you an accounting of the folder searches it's doing and what files it's finding.  That might make it obvious what's going wrong, so you might spot it right off the bat, but if not you can upload it here and I'll take a look.  You might want to upload your Settings.txt as well so I can compare the log report to what the settings say should be happening.

**Comment by mjrgh** [comment]
Just pinging to see if you're still there - I can't investigate without more information.

**Comment by dch850** [comment]
Hi, 

I've spent a couple on hour on that and checked the log on the last week but.... impossible to reproduce, everything was going well and my new tables are found systematically I can't understant what I was doing wrong or differently before.

Sorry for made you wasting time but it seems that, as I felt it, the issue was between the screen and the chair. 
I guess we can close this one

**Comment by mjrgh** [comment]
Sounds good - I'll close this for now.  Let me know if it comes back!
