### ISSUE TITLE
no tables found - vpx

### ISSUE THREAD

**Issue by dexje** [mjrgh/PinballY#3]
i´ve configured the paths for vpx, but still the frontend does not find any tables.
since there are not many variables i can manually configure for the "discovery process" .. it guess there has to been an issue.

which further details of my setup do you need?

**Comment by mjrgh** [comment]
Also, please check your options to see if the "Hide Unconfigured Games" checkbox (under the Game Wheel page) is checked.  If so, you can do one of two things:

* If you want to see unconfigured games all the time, un-check the box

* If you want to see unconfigured games specifically, bring up the Operator Menu and select Show Unconfigured Games
