### ISSUE TITLE
FFmpeg error

### ISSUE THREAD

**Issue by gate001** [mjrgh/PinballY#34]
Hi,
It's me again with another problem.
I am no longer able to record my media.
Before I had no problem, the only difference is the update to the Beta 2 (pinballY files overwritten by those in the ZIP file)

Here is the log:
[PinballY.log](https://github.com/mjrgh/PinballY/files/2810686/PinballY.log)

**Comment by mjrgh** [comment]
You're getting a "file not found" error launching ffmpeg.exe according to the log, so I have a guess:

Check your PinballY folder to see if there's a folder called ffmpeg64.  If so, try renaming that folder to ffmpeg and giving the capture another go.  

My ZIP builder script had an error that gave the folder the wrong name.  I've fixed it, but you probably have the copy of the ZIP that had the naming error.

**Comment by mjrgh** [comment]
Great!  I've fixed my ZIP builder script, so hopefully this won't happen again in future updates.
