### ISSUE TITLE
Rating & Categories problems 

### ISSUE THREAD

**Issue by wim312** [mjrgh/PinballY#35]
When you have tables with the same name and same type (vpx) but other manufacturer/year then it's not possible to set different rating / categorie for both tables.
ex.
Circus (Gottlieb 1980).vpx
Circus (Zaccaria 1977).vpx

**Comment by wim312** [comment]
When you have tables with the same name and same type (vpx) but other manufacturer/year then it's not possible to set different rating / categorie for both tables.
ex.
Circus (Gottlieb 1980).vpx
Circus (Zaccaria 1977).vpx

**Comment by wim312** [comment]
GameStats.csv
Circus.Visual Pinball X,,,,,,

**Comment by mjrgh** [comment]
Yeah, this is definitely a limitation with the current ID scheme.  I'll have to think about it - I'll see if I can add more information to the key without breaking everyone's existing configuration.

**Comment by mjrgh** [comment]
I changed it in the Beta 3 to include the manufacturer and year in the GameStats key, so it should now be able to distinguish entries for games with shared titles as long as they have different manufacturers and/or release years.  Existing GameStats files should automatically update to the new format the first time you run the new version, so existing data should be carried forward.  In the case of your existing file with the single Circus.VisualPinball X entry, it should be "claimed" by whichever Circus the program tries to look up first, and the other one should automatically get its own new row.
