### ISSUE TITLE
Bug - Startup Video (dmd) does not play on Real DMDs

### ISSUE THREAD

**Issue by kaicherry** [mjrgh/PinballY#37]
Adding this video does not play on a Real DMD at startup or at any time. Last video played on DMD is played instead.

Reproducable last two releases, latest "freeze" dlls, PINDMD3, 64-bit PinballY

**Comment by mjrgh** [comment]
Indeed, there's no support as yet for playing a startup video on the real DMD.   I didn't think about adding that.  It should be pretty easy to add since the video playback infrastructure is already there.

**Comment by kaicherry** [comment]
There is more, different issue making new post, stand by ;)

**Comment by mjrgh** [comment]
Added to beta 6.
