### ISSUE TITLE
Cannot launch dmdext.exe as "Run Before" for mirroring Pinball FX3 without hanging process

### ISSUE THREAD

**Issue by kaicherry** [mjrgh/PinballY#44]
Covered by [NOWAIT] per MJR

**Comment by mjrgh** [comment]
What you're looking for is the [NOWAIT] option.

http://mjrnet.org/pinscape/downloads/PinballY/Help/SystemOptions.html

**Comment by kaicherry** [comment]
Thank you, sir, removing :)
