### ISSUE TITLE
Default Backgrounds - Default DMD

### ISSUE THREAD

**Issue by gate001** [mjrgh/PinballY#46]
In one of my tables I used the pinballY default DMD.
With this new version that table have an error (file not found). I had to copy the file DefaultDMD.png (from \assets folder) to the \media\image folder (and rename it with a space) to eliminate that error.

**Comment by mjrgh** [comment]
Did you install from the ZIP?  This version rearranged the assets folder a bit, and the ZIP didn't have the updated files.  If you grab this file:

http://mjrnet.org/pinscape/downloads/PinballY/assets-20190214.zip

and unzip it into your existing folder, it should give you the missing files.

**Comment by gate001** [comment]
I used the ZIP file to overwrite the existing files.
Tonight I will erase the \asset folder and copy those of your ZIP. I will also delete the "Default DMD.png" file from the \media\image folder.
Do I have to delete the files I copied in \media\image\Button Sounds? Because I also had no sound.

**Comment by mjrgh** [comment]
Yes, the button sounds were moved as well.

**Comment by gate001** [comment]
It's perfect, it works.
At the next Beta version I will redo a clean installation because I think I have some files of the old version that remains.

Rename the PinballY folder as backup.
Create a new PinballY folder (with the same name as the previous one)
Unzip the new beta version in the new folder.
Copy the previous settings.txt file to the pinballY folder.
Copy the previous "media" folder to the pinballY folder.

Is this the best way to make an update? Do I forget a file?

**Comment by mjrgh** [comment]
You'll also want to copy over GameStats.csv, plus your Database folder tree, if you're keeping the XML game list files under the PInballY folder.  

Note that Windows Setup is pretty good about handling this sort of update operation, if you want to switch over to that at some point.  It keeps records on which files it installs, so when it does an update, it automatically cleans up files that are no longer present, adds files that are newly added, and leaves intact anything that's been modified.

**Comment by gate001** [comment]
OK, thanks
