### ISSUE TITLE
Load PinballY with a delay

### ISSUE THREAD

**Issue by gate001** [mjrgh/PinballY#47]
I changed television and pinballY no longer works.

I did some testing and the problem is not pinballY but my new TV.
I did some testing. The result are:
-Without the new TV plugged in (not plug into a wall socket) windows detects 2 screens.
-When connected to the wall socket (but not turned on), windows detects 3 screens.
-When I turn on my screen, windows loses the new screens for about 3 seconds before detecting it again.

This causes pinballY to load since it detects 3 screens, but when I open my new tv and Windows detect only 2 screens, my windows move to the two remaining screens but is not putting it back when my third screen is detected so I have the playfield on the DMD screen.
I work around this problem by using a delay before loading pinballY (with a .bat file) and using the start pinballY manually option.
Can you add an option in pinballY to wait X seconds before opening? I think this option can also serve people whose computer is less fast (old computer). When they startup windows, the CPU/HDD are overloaded and the intro video of pinballY could be choppy.

**Comment by mjrgh** [comment]
Have you tried the "Wait for monitors to come online at startup" option, in the Startup page of the options dialog?  That was designed for exactly this situation, so hopefully it'll do the trick.  If you're already doing that, let me know and we can look into why it's not waiting.

**Comment by gate001** [comment]
this option works fine, except that in my case, Windows detect three screens (when the TV is a off) so pinballY starts (since I have three screens), I turn on the TV, then Windows detects two screens and move playfield  on DMD screen. After 3 sec. Windows detects again three screens but does not move my playfield to this screen.

**Comment by mjrgh** [comment]
Okay, I haven't seen Windows do that before.  I think you're right that you'll just need a fixed delay time to deal with that.  The point of the "wait for N monitors" was to avoid any unnecessary delays by actually checking when the monitors are ready, but if the monitors are going to pop in and out of existence like that, that won't quite do the trick.

Before I add something to the PinballY options, though, let me propose what might be a better way for you.  If I add it as a PinballY option, you'll have to endure the delay **every** time you start the program, even when the system has already been up and running for a long time.  But this is only an issue during the initial system boot-up, right?  So how about this:  Windows Task Scheduler has an option to delay a task after its triggering condition for a desired interval.   If you're using PinballY's startup option, it works by creating one of those Windows Task Scheduler tasks.  You can edit that as follows:

- Run Windows Task Scheduler (Windows+R, type Task Scheduler)
- Click on Task Scheduler Library in the list on the left
- Find the PinballY Startup Task in the task list
- Right-click on it and select Properties
- Go to the Triggers page in the properties dialog
- Select the "At log on" trigger and click Edit
- Under Advanced Settings, check the box for "Delay task for:" and enter a suitable delay period
- "OK" out of the dialogs, exit Task Scheduler

Will that work for you?

**Comment by gate001** [comment]
Yes, that will do the trick
thanks

**Comment by mjrgh** [comment]
In the beta 7, there's a new post-logon delay setting in the options dialog.  It does the same thing as described above, just without the need to use Task Scheduler to modify the task.

There's also a new separate setting in the "Wait for monitors" section that lets you add a delay time after all monitors are recognized, just in case that's a more reliable approach for some systems.

Hopefully one or the other of these will handle it for anyone in the same situation!
