### ISSUE TITLE
"Burn in" potential

### ISSUE THREAD

**Issue by kaicherry** [mjrgh/PinballY#49]
So I have noticed that the wheel positions there on the far edges might be a "burn in" issue, yes even on a modern display, because even as the wheel goes thru attract mode, essentially, the "image" is the same - see "Tarcisio - style Wheels" for what I mean.

I am not exactly sure how this would be approached, maybe hide all wheels after _n_  idle time, run some "busy screen saver" video?

Photos attaching.. This display is not more than a couple months old

![image](https://user-images.githubusercontent.com/170258/53922326-b8836880-4028-11e9-85ef-c9872dcd3291.png)
![image](https://user-images.githubusercontent.com/170258/53922343-c9cc7500-4028-11e9-9eae-e24717a780f7.png)

**Comment by mjrgh** [comment]
Probably the thing to do is to just hide the wheel images entirely in attract mode.

**Comment by kaicherry** [comment]
Like until a button is actually touched? I think that would actually work/address this...

**Comment by mjrgh** [comment]
New Attract Mode setting (enabled by default) in Beta 8 lets you hide wheel icons when in attract mode.

**Comment by kaicherry** [comment]
Nice! I installed like 15mins ago, read nothing, went for a coffee, came back, no wheel images.

I actually, heh, shouted "Yeah!" out loud :)
