### ISSUE TITLE
Pinball FX3 Steam not launching to table

### ISSUE THREAD

**Issue by Nutmegz** [mjrgh/PinballY#51]
When using PinballY for Pinball FX3/FX2 on steam, it does not launch into the table. In the command line  parameters:

System6.Parameters = -applaunch 442120 "-table_[TABLEFILE]"

does [TABLEFILE] still have the file extension with it? If it does, this what makes it not launch right into the table.

**Comment by mjrgh** [comment]
If you check the log file (PinballY.log, in the program folder; make sure Table Launch is checked in the Log File options), it'll show you the exact command line being generated, with all of the substitution variables substituted.  Check that and see if that helps.  It's entirely possible that FXn has made a change to their command line format, so you might want to check with them to see if they did something that requires updating the launch parameters.

**Comment by Adeysan** [comment]
PFX3 (now?) doesn't like having the .pxp extension passed to it on the command line, but it is being added automatically by PinballY before launch:

launch: full table path C:\Program Files (x86)\Steam\steamapps\common\Pinball FX3\data\steam\Alien_Isolation

table launch: table file C:\Program Files (x86)\Steam\steamapps\common\Pinball FX3\data\steam\Alien_Isolation doesn't exist; try adding extension -> C:\Program Files (x86)\Steam\steamapps\common\Pinball FX3\data\steam\Alien_Isolation.pxp

table launch: file + extension (C:\Program Files (x86)\Steam\steamapps\common\Pinball FX3\data\steam\Alien_Isolation.pxp) exists, using it

Original> -applaunch 442120 -table_[TABLEFILE]

Final > -applaunch 442120 -table_Alien_Isolation**.pxp**

**Comment by mjrgh** [comment]
Okay, I'll add add new substitution variable - let's call it [TABLEFILEBASE] - that lets you get at the table file name stripped of any extension.  

I'll also change the default settings to use it for FX3.  Do you know if this applies to FX2 as well?

**Comment by Nutmegz** [comment]
Yes it applies to FX2 as well

**Comment by mjrgh** [comment]
The new [TABLEFILEBASE] variable is in the beta 11 - give that a try and see if it works for you.  (You'll have to change your FX2 and FX3 command line settings to use the new variable, of course, as your existing settings are always preserved across versions.)
