### ISSUE TITLE
fullscreen \\.\Display?

### ISSUE THREAD

**Issue by montygood** [mjrgh/PinballY#53]
Full screen on display in the ini set so that the backglass is always shown on the display2 and the playfield on display1 and DMD on the display3 would be a great function so you could also use other emulators with display switch.
the same as possible with Pinballx?

**Comment by mjrgh** [comment]
I'm afraid I don't understand what you're asking for.  Could you explain further?

**Comment by montygood** [comment]
I mean a real full frame like hyperpin.
[Video]
Playfield_Monitor   = Primary
Backglass_Monitor   = Secondary

sorry for me Englisch im swiss people

**Comment by mjrgh** [comment]
Sorry, I still don't understand - are you saying you just want a full-screen mode?  Have you tried full-screen mode?  

Right click the window -> select FULL SCREEN from the menu

**Comment by montygood** [comment]
the problem is if exit game with switch monitor the backglas is over the playfield i must press th fullscreen button tow times for correct this

**Comment by mjrgh** [comment]
Okay, let’s fix that, then. 

1. What game is this?
2. How are you doing this “switch monitor” operation that’s causing the trouble? Full details, please - pretend I can’t see what you’re doing with the mouse/keyboard from here.

**Comment by montygood** [comment]
Ligthgun games on Demul emu with displayswitch /clone display for gaming by exit is dthe BG over PF

**Comment by montygood** [comment]
Scummvm emu is the same problem run fine by exit BG over PF both by Fullscreen i must script running find BG and press too times F12 for correct it

**Comment by montygood** [comment]
widows 10 i use Displayswitch /clone and by exit displayswitch /extend

**Comment by mjrgh** [comment]
> ... and press too times F12 for correct it

Why F12?

**Comment by mjrgh** [comment]
> i use Displayswitch /clone and by exit displayswitch /extend

Could you explain your complete setup for me?  Remember, I can't see what's on your computer.

**Comment by montygood** [comment]
with this autoit it works for me:

If not $CmdLine[0] Then Exit
HotKeySet("{ESC}", "menu")
$IniFile = @scriptdir & "\run\" & $CmdLine[1] & ".ini"
$run = IniRead($IniFile, "Settings", "run", "")

RunWait("DisplaySwitch.exe /clone")
shellexecute("C:\PinballX\Plugins\gunan.exe", "", "", "runas")

Run($run,@scriptdir)
Run("C:\PinballY\Plugins\LEDBlinky\LEDBlinky.exe " & $CmdLine[1] & " demul")
ProcessWaitClose("demul.exe")

RunWait("DisplaySwitch.exe /extend")
Run("C:\PinballY\Plugins\LEDBlinky\LEDBlinky.exe 2")
shellexecute("C:\PinballX\Plugins\gunaus.exe", "", "", "runas")
**WinWaitActive("[CLASS:PinballY.FrameWinClass]")
send("#+{LEFT}+{LSHIFT}")**

Func menu()
	ProcessClose("demul.exe")
EndFunc

**Comment by montygood** [comment]
F12 i have bevor set this key to fullscreen

**Comment by montygood** [comment]
you can close this

**Comment by mjrgh** [comment]
Okay, glad you found a solution.  I'll close it out.

For what it's worth, I think you're doing this the hard way.  It should be easier with Run Before and Run After commands instead of the external scripting.
