### ISSUE TITLE
FP should use FPLoader

### ISSUE THREAD

**Issue by maperks** [mjrgh/PinballY#55]
The default program for FP tables is Future Pinball.exe. However that has a lot of problems especially in cab mode. Everyone uses BAM and  FPLoader. For now I explicitly changed the executable to be BAM\FPloader.exe. Can you make this the default?

**Comment by mjrgh** [comment]
No, I don't think so.  I'd rather keep the more standard setup the default.  The FP + BAM setup is listed as one of the recipes in the help section for people using that setup.
