### ISSUE TITLE
Finding FP Tables

### ISSUE THREAD

**Issue by maperks** [mjrgh/PinballY#57]
It seemed that PinballY had a problem with finding FP tables that were already available in d:\future pinball\tables. I had to explicitly add this folder to the PinballY configuration. Then everything worked fine.

**Comment by mjrgh** [comment]
Do you have a test case that can be reproduced here?

**Comment by maperks** [comment]
I see the problem now. Because FPLOADER is in the BAM directory, it is expecting TABLES to be under BAM when in fact it is under ..\TABLES.

The recipe needs to be changed to specify one of the following:
1. ..\tables (it works !)
2. c:\future pinball\tables
3. move tables folder to be under BAM directory (probably not good)

**Comment by mjrgh** [comment]
Changing to ..\table is probably the best approach, as it's a relative path that will adapt to whatever folder path you use for VP itself.  

Is this reliable enough to make it the universal recipe?  In other words, does BAM **always** go in a <path to FP>\BAM, or is this something everyone decides at install time?  If everyone picks their own idiosyncratic location, it's harder to suggest a fixed recipe that'll work for everyone.

**Comment by maperks** [comment]
I went to the source: TerryRed. Here is his complete [writeup on FP configuration](https://www.vpforums.org/index.php?showtopic=36449). You will find similar on other websites. 

> ...This is a MUST, for complete compatibility with all tables...

So I would go further and make my original point. The default for FP should be to use BAM/FPLoader. A recipe is not enough.

BTW I only have about 7 FP tables (out of 51) because they have the best or only implementation of a particular table..

**Comment by mjrgh** [comment]
> The default for FP should be to use BAM/FPLoader. A recipe is not enough.

I'm not seeing it.  BAM is an add-on, right?  The way I read TerryRed's "MUST" is that you "must" set it up that way if you want to use BAM.  I mean, the very title of the topic is "How Future Pinball 'should' be setup for BAM [etc]...". 

And separately, was this meant as an answer for my question about paths?

**Comment by maperks** [comment]
Well in my experience FP just doesn't work right without FPLoader doing it's thing, especially in a portrait cabinet mode. His thread title is "**How Future Pinball "should" be setup with a new clean install for a cabinet"**

If you follow TerryRed's instructions/tutorial then yes it is always in BAM and that is almost 100% guaranteed.
