### ISSUE TITLE
Default place for VPX media

### ISSUE THREAD

**Issue by maperks** [mjrgh/PinballY#58]
When I setup PinballX I decided to use the name "VP 10" for the configuration. PinballY could not find this folder and so no media was loaded. Once I changed everything in PinballX to use "Visual Pinball X" then everything worked. I think this is a matter to reading the PinballX configuration file and using that to set the PinballY configuration. To make things simple this only needs to be done once when PinballY is loaded and the user selects to use PinballX media.

**Comment by mjrgh** [comment]
Did you try explicitly setting the Media Folder and/or Database Folder options under the system setup?  See Help -> Options -> Systems and Help -> Files & Folders for how this works.
