### ISSUE TITLE
Backglass Borderless option

### ISSUE THREAD

**Issue by sebinouse** [mjrgh/PinballY#6]
Is it possible to have a borderless option for the backglass so as to get rid of the windows top bar of the backglass window (the same way as DMD or Instruction card window) ?

no other issue to report so far, I keep testing

**Comment by mjrgh** [comment]
Just right click in the window and select Full Screen.

**Comment by sebinouse** [comment]
I know but I don't want full screen ... my third screen for DMD masks about 2cm of the bottom of the backglass screen
![backbox](https://user-images.githubusercontent.com/9035443/45538110-69d9dc00-b806-11e8-9098-20751271c418.png)

I was just thinking about an option in the right clic menu of the backglass window

**Comment by mjrgh** [comment]
Oh, I see.  Yeah, that should be easy to implement.  I'll look into it for the next update.

**Comment by sebinouse** [comment]
Feature working great ! Thanks !

**Comment by mjrgh** [comment]
Starting with Alpha 21, "Show window borders" is an option in the right-click menu for the backglass window, so you can get rid of the frame now.
