### ISSUE TITLE
Instructions not shown during game play

### ISSUE THREAD

**Issue by maperks** [mjrgh/PinballY#60]
Per my email, I have setup a 3rd monitor just to display instructions (which is BTW a neat addition that PinballX does not have). I have playfield and backglass monitors as well as a Real DMD.

When PinballY starts FPLauncher, the 3rd monitor is left undisturbed and instructions show. 

When Visual Pinball is started (9 or X), the 3rd monitor is blacked out. Further exploration shows the following conditions:
1. Using non full screen for the instructions window results in just that window going black.
2. Using non full screen for playfield shows that starting a table using VPX does not disturb the instruction window. 

This isolates the problem to the way that PinballY is starting VPX or VP9 but not FP.

**Comment by mjrgh** [comment]
Try this:

Operator Menu -> Game Setup -> Edit Game Details -> check the "Instruction Card" box under "Keep the following PinballY windoiws open (showing videos/graphics) while running this game".

**Comment by maperks** [comment]
I wasn't aware of that option. It does work but only on a per table basis. A global option would be nice as well. 

It doesn't completely explain why I don't need this setting for FP but understand that Visual Pinball works differently.

**Comment by maperks** [comment]
BTW It only works for FP when it is a window and not full screen. I have added this setting to 3 tables, only 48 to go. I'm so glad I don't have 300 tables.

**Comment by mjrgh** [comment]
Beta 12 has options to select the "keep open" status globally and per system, in addition to the per-game settings.
