### ISSUE TITLE
service menu not working properly and can't change selected table

### ISSUE THREAD

**Issue by EclecticEngineer** [mjrgh/PinballY#61]
I just installed PinballY and cannot use the service menu to set up any tables. I also can't select any other tables even though it says "All Tables (96 Matches)".

Keyboard input works fine to bring up options. Using a keyboard I have no problem typing "o" to bring up options and modify button keybindings, but for some reason, typing "0" only sometimes brings up the service menu. It seems to most consistently come up if I type "o" first then hit esc to close the options popup. At that point the title of the table shows without "Never played" under it, at which point the service menu can be brought up by typing "0".

But at that point no buttons do anything except beeping. I tried binding the service menu up and down buttons to something else (like arrow keys or w and s), but no matter what I do, all I get is beeping when I try to either select something or move the menu selection.

If I hit spacebar once in the service menu, it just exits the service menu and shows the current game with "Never played" under it again.

Not really sure what to do. I tried hitting every button on the keyboard both in and out of the service menu, but nothing does anything except sometimes beep at me.

**Comment by mjrgh** [comment]
Try the beta 11.
