### ISSUE TITLE
DMD images and Videos not scaled to real DMD

### ISSUE THREAD

**Issue by maperks** [mjrgh/PinballY#62]
I have a real DMD that is 128x32. If a real DMD image or video is not found then the regular DMD image or video is loaded. Unfortunately they are different sizes and not scaled to my DMD.

**Comment by mjrgh** [comment]
Do you have an example file?

**Comment by maperks** [comment]
You may also notice that there is a problem with the RGB colors, probably in the wrong order. I wrote a separate defect on that problem. See [62.zip](https://github.com/mjrgh/PinballY/files/3057183/62.zip) too.

**Kiss**

![KISS](https://user-images.githubusercontent.com/41599843/55773536-9b421f80-5a56-11e9-8e2a-9e29e5ae9c1c.png)
![Pinbaly KISS](https://user-images.githubusercontent.com/41599843/55773537-9b421f80-5a56-11e9-82ea-9cce9961e39e.jpg)

**Xenon**

![Xenon](https://user-images.githubusercontent.com/41599843/55773549-aac16880-5a56-11e9-8774-433861365553.png)
![PinballY Xenon](https://user-images.githubusercontent.com/41599843/55773552-adbc5900-5a56-11e9-8743-9c3cad3764bb.jpg)

**Comment by mjrgh** [comment]
This should be fixed in the beta 12.
