### ISSUE TITLE
trigger PBYWheelNext/Prev

### ISSUE THREAD

**Issue by gate001** [mjrgh/PinballY#64]
Hi mjr,

The trigger PBYWheelNext/Prev activate when we are in a menu and we change lines. I think they have to trigger only when we change tables.
This trigger is the duplicate of the PBYFlipperLeft/Right trigger.

**Comment by mjrgh** [comment]
I just checked, and PBYWheelNext/Prev don't appear to get triggered when a menu is active.  Where have you seen that happen?  Are you sure it's those specific events that you're seeing triggered?

**Comment by gate001** [comment]
Sorry, it's my mistake. I changed the "PF Left Effects MX" field in the configtool but left the "PF Left Flashers MX" field with the default. Thats the one that has the $ PBYMenuUp/Down trigger.

**Comment by mjrgh** [comment]
Great, I'll close this out.
