### ISSUE TITLE
The color order appears wrong on Pin2DMD

### ISSUE THREAD

**Issue by maperks** [mjrgh/PinballY#65]
For my color Pin2DMD, the RGB color order appears to be incorrect. I used the following file (128x32) as my default DMD image: 
![ufo pinball obession small](https://user-images.githubusercontent.com/41599843/55773754-bd886d00-5a57-11e9-8a75-35ca370658d0.png)

But the colors come out incorrectly as mentioned in #62. Interestingly I get different results with Beta 9 and Beta 11. See [65.zip](https://github.com/mjrgh/PinballY/files/3057216/65.zip)

**Comment by blc29seb** [comment]
hi 
I have the same problem
see my message : https://github.com/mjrgh/PinballY/issues/41#issuecomment-471182237
i try with a test patern Red Green Blue (RGB) and i I saw that the red and blue colors were reversed (BGR)

![pin2dmdColor](https://user-images.githubusercontent.com/14741944/57983520-00743200-7a53-11e9-9408-3101a2c68c55.jpg)

**Comment by mjrgh** [comment]
This should be fixed in the beta 12.
