### ISSUE TITLE
Error message is displayed when not needed

### ISSUE THREAD

**Issue by maperks** [mjrgh/PinballY#66]
Bring up the game details dialog and make only one change which is to check "the keep instructions card" checkbox. The error screen to the left appears:
![Capture1](https://user-images.githubusercontent.com/41599843/56004380-91a3fc00-5c90-11e9-93cb-67b118b07d0d.PNG)

This is incorrect behavior as nothing else changed. Clicking on "Yes" shows the error message panel. Looking at the filenames, the code is trying to rename a file to itself and tripping over that fact. 
![Capture2](https://user-images.githubusercontent.com/41599843/56004391-aa141680-5c90-11e9-8ae5-d7677d838d28.PNG)

Both problems described above should be fixed:
1. No other changes do not result in a rename
2. When a rename occurs it should only happen if indeed the two names are different.

**Comment by mjrgh** [comment]
I'm afraid it doesn't reproduce for me with random games - if you can figure out the specific condition that causes it, I'll be able to look into it.

**Comment by maperks** [comment]
I have reproduced it about 50% of the time - it is not everytime and seems to occur only once per game. The only other thing that might be different is that I'm using a PinballX media folder rather than the PinballY one.

It obviously happens because of the screen shots. I think some checks in the code to only rename stuff when needed is appropriate. But I understand the problem of how you are going to test it if you cannot reproduce it.

**Comment by maperks** [comment]
I think I understand the problem now. Take a look at the difference report below between two versions of the Pinballx.xml file:
![Capture](https://user-images.githubusercontent.com/41599843/56011183-0fc1cc00-5cac-11e9-8d42-15e7878557ab.PNG)
The one on the left is the original. Rightly or wrongly I name all my games in PinballX with just the name and no year or manufacturer. Then PinballY sees the name, does a database lookup and automatically changes the name to include the year and manufacturer. PinballY also adds the IPDB tag as well but interestingly not the actual value (I suppose the user has to do that). This explains why PinballY thinks there is a name change.

I'm not sure any of the media resources are changed. PinballY does try to rename the Instruction Card (without manufacturer and year in the name) and fails on the rename operation.

**Comment by maperks** [comment]
I have closed the issue. I now understand how PinballX and PinballY work with respect to the naming of tables and in fact I can leave in the year and manufacturer using the (MMMMMM YYYY) syntax. The first automatic rename does no harm per se. The second error message is because I have 2 instruction card files.
