### ISSUE TITLE
Future Pinball Tables do not load

### ISSUE THREAD

**Issue by Sphinx0402** [mjrgh/PinballY#68]
I have the problem, that Future Pinball tables are not loading in PinballY. I am using BAM, but also after configuring the settings in options like the Help describes it, the tables are not loading, after a short time, PinballY returns back to the Menu. But, I have seen in Task Manager, both .exe (FPloader.exe and Future Pinball.exe) are running.

**Comment by Sphinx0402** [comment]
After some finetuning and moving the fpt from subfolders to table folder, future pinball tables are loading. But now, I have the problem, that FutureDMD.exe not loads and stops like in PinballX. How could I paste the command line in options for start and stop futuredmd.exe?

**Comment by mjrgh** [comment]
I'm afraid I don't know much about FutureDMD.  If that's something you want to run alongside FP while it's running, running it as a Before command is probably the right approach.  Maybe try asking on the forums for more help? 

I'm closing this out since it sounds like you solved the original issue.

**Comment by mandragora99** [comment]
hello mjrgh

I also have a little problem
Maybe you can help me briefly

I took the configuration from your website.
http://mjrnet.org/pinscape/downloads/PinballY/Help/SystemOptions.html

System class: Future Pinball
Program EXE: BAM \ FPLoader.exe
Parameters: [TABLEPATH] / open "[TABLEPATH] \ [TABLEFILE]" / play / exit / arcaderender
Window Mode: Minimize
Process name: Future Pinball.exe
Table folder: .. \ Tables
Table extension: .fpt
Startup Keys: [click playfield]
DOF Prefix: FP

These are the settings of my settings in PinballY

# Future Pinball
System4 = Future Pinball
System4.Class = FP
System4.Exe = C: \ Games \ Future Pinball \ BAM \ FPLoader.exe
System4.ShowWindow = SW_SHOWMINIMIZED
System4.Environment =
System4.TablePath = C: \ Games \ Future Pinball \ Tables
System4.Parameters = [TABLEPATH] / open "[TABLEPATH] \ [TABLEFILE]" / play / exit / arcaderender
System4.DefExt = .fpt
System4.StartupKeys = [click playfield]
System4.DOFTitlePrefix = FP

After I started PinballY the tables are shown to me and they try to start. However, only the Futurepinball window appears and the loading ends at some point.

Can you please tell me what I'm doing wrong here or how I can fix the problem.

Thank you for your help.
