### ISSUE TITLE
Enable Pinbally to use startup parameters (FX3 table modes)

### ISSUE THREAD

**Issue by skullmonkey911** [mjrgh/PinballY#70]
FX3 supports some startup parameter to enter special table mdoes (e.g. hotseat mode, classic mode, etc.) It would be nice for Pinbally to support lit. Popper has a basic feature, but I don't like it and I like Pinbally much more.

my "dream" is, to have in the (key 1) menue some  play options.
For Example Play with Hotseat2 or two players (wihich is -hotseat2 parameter).

I think a name/value list in the game setup named "table modes" would do the trick. Then the 1-menü need to read out this list and on launch add the argrument to the *.exe invokation.

**Comment by mjrgh** [comment]
This has been raised before, and it was actually the motivation for adding Javascript.  I didn't want to build in special-case handling for each system, but there are so many potential variations that it's hard to generalize into a static list of options.  Javascript is the better approach here, in my opinion.  So I added a worked example showing how to implement this specific sort of thing:

http://mjrnet.org/pinscape/downloads/PinballY/Help/CustomPlayModesExample.html
