### ISSUE TITLE
Child proctection feature

### ISSUE THREAD

**Issue by skullmonkey911** [mjrgh/PinballY#71]
Goal: Lock/Exclude some tables by default when key is set in game setup.

Only show if key combination was entered (e.g. flipleft, Flipleft, Flipright, launch, etc) Unlock entry in key 1 menu is necessary. Game setup entry needs also an authorisation then...

Reason: My Kids don't need to see some Tables....

**Comment by mkalkbrenner** [comment]
> Only show if key combination was entered (e.g. flipleft, Flipleft, Flipright, launch, etc) Unlock entry in key 1 menu is necessary. Game setup entry needs also an authorisation then...

Another option would be a button behind the coin door - in other words a specific button as trigger.

PinballY already has a table filter/lists concept. So it might be an extension to that concept.

**Comment by mjrgh** [comment]
I think this is a little too much of a niche feature to build in, but it can be done easily in Javascript.  I added a worked example showing how:

http://mjrnet.org/pinscape/downloads/PinballY/Help/FamilyFilterExample.html

(That uses a menu option in the Operator Menu to turn "family mode" on and off.  If you're really attached to the original proposal to use an Easter Egg button sequence, that could easily be implemented in Javascript as well, using "keydown" events.  I could add an example of that if you need help with it.)

**Comment by skullmonkey911** [comment]
Hi mjrgh,

maybe I just don't understand the example, but in the first paragraph you write using a Coin Door Service Button. But in the code example this is not descriped. Is this correct? I think I have to include a keydown event here...

Regards,

Stephan

**Comment by mjrgh** [comment]
Nope, no keydown event needed.  The part about the service button refers to the usual wiring in a pin cab of digit "0", which in PinballY opens the Operator Menu, to the coin door service panel Enter button.
