### ISSUE TITLE
Pinbally has problems remembering screen positions

### ISSUE THREAD

**Issue by skullmonkey911** [mjrgh/PinballY#73]
Starting setting up my new pinball hardware I switched frontends from PinUpPopper to Pinbally and I like it.

**But** I have a big problem.

First of all, I have 3 screens. My Playfield is Display 1, LCDDMD Display 2 and my Backglass Display 3. 

To get VPX going I've changed the order to 
PF =1, 
BG =2 and 
DMD =3

in the Nvidia Settings. Windows now also shows the changed order. 

And it works this way with VPX, FX3 and PinUPPlayer (PUPPacks).

In Pinbally I place all my screens (MainWindow on PF as Fullscreen, Backglass to Backglass as Fullscreen and DMD to DMD. 
If I now exit pinbally and start it again. All my displays are out of order (all on playfield).

I checked pinbally setting properties manually with no luck. The numbers in there seems to be wired!

I use startup videos as well... Also disarranged.

I need some help. Seems to be I'm the only one with this specific problem...

**Windows version**
I'm using Windows 10 Home, with Zotac GTX1070.

**Comment by skullmonkey911** [comment]
Here are the setting after arranging the screens:

PlayfieldWindow.Position = 0,0,3840,2160
PlayfieldWindow.Rotation = 90
PlayfieldWindow.MirrorHorz = 0
PlayfieldWindow.MirrorVert = 0
PlayfieldWindow.FullScreen = 1
PlayfieldWindow.Maximized = 1
PlayfieldWindow.Minimized = 0
BackglassWindow.Position = 3990,304,5232,822
BackglassWindow.Rotation = 0
BackglassWindow.MirrorHorz = 0
BackglassWindow.MirrorVert = 0
BackglassWindow.Visible = 1
BackglassWindow.FullScreen = 1
BackglassWindow.Maximized = 0
BackglassWindow.Minimized = 0
DMDWindow.Position = 5538,-47,6782,637
DMDWindow.Rotation = 0
DMDWindow.MirrorHorz = 0
DMDWindow.MirrorVert = 0
DMDWindow.Visible = 1
DMDWindow.FullScreen = 1
DMDWindow.Maximized = 0
DMDWindow.Minimized = 0

Just closing and reopenening I get this:
PlayfieldWindow.Position = 0,0,3840,2160
PlayfieldWindow.Rotation = 90
PlayfieldWindow.MirrorHorz = 0
PlayfieldWindow.MirrorVert = 0
PlayfieldWindow.FullScreen = 1
PlayfieldWindow.Maximized = 1
PlayfieldWindow.Minimized = 0
BackglassWindow.Position = 921,867,2163,1385
BackglassWindow.Rotation = 0
BackglassWindow.MirrorHorz = 0
BackglassWindow.MirrorVert = 0
BackglassWindow.Visible = 0
BackglassWindow.FullScreen = 1
BackglassWindow.Maximized = 0
BackglassWindow.Minimized = 0
DMDWindow.Position = 578,683,1822,1367
DMDWindow.Rotation = 0
DMDWindow.MirrorHorz = 0
DMDWindow.MirrorVert = 0
DMDWindow.Visible = 0
DMDWindow.FullScreen = 1
DMDWindow.Maximized = 0
DMDWindow.Minimized = 0

All Screens are now displayed on the playfield. I have to hide DMD and BG then... Playfield position is always okay...

**Comment by skullmonkey911** [comment]
I tried this manuell settings:

PlayfieldWindow.Position = 0,0,3840,2160
PlayfieldWindow.Rotation = 90
PlayfieldWindow.MirrorHorz = 0
PlayfieldWindow.MirrorVert = 0
PlayfieldWindow.FullScreen = 1
PlayfieldWindow.Maximized = 1
PlayfieldWindow.Minimized = 0
BackglassWindow.Position = 3840,0,5760,1080
BackglassWindow.Rotation = 0
BackglassWindow.MirrorHorz = 0
BackglassWindow.MirrorVert = 0
BackglassWindow.Visible = 1
BackglassWindow.FullScreen = 1
BackglassWindow.Maximized = 0
BackglassWindow.Minimized = 0
DMDWindow.Position = 5760,0,7040,720
DMDWindow.Rotation = 0
DMDWindow.MirrorHorz = 0
DMDWindow.MirrorVert = 0
DMDWindow.Visible = 1
DMDWindow.FullScreen = 1
DMDWindow.Maximized = 0
DMDWindow.Minimized = 0

Doesn't help. Changed plugs at GFX and a lot of other things. I'm frustrated. Will Setup Popper again in parallel :(

**Comment by mjrgh** [comment]
I have no guess about what's going on.  Are you doing something that's changing the desktop layout dynamically between program invocations, or something like that?  The only thing I can think of is that PinballY is running with one desktop layout when you arrange the windows, so it saves the positions with the monitor coordinates based on that layout, and then the next time you run there's a different layout in effect, so the saved monitor coordinates are no longer valid.  Any chance something like that is going on?  If so, is there any way you can arrange things so that the same layout is always in effect when you start PinballY?

**Comment by skullmonkey911** [comment]
Hi,

hard to say, but maybe I have a hunch. As I said, I setup Popper Menu in parallel. There I have no problems with the positions, but I had an issue when exiting vpx. The Screens went black for a short time. I found out, that this is releated with HDR Setting of my Acer 4k display. I turned HDR off for now. Since then I did checked Pinbally again. I will do that tomorrow and get back to you.

Cheers 

Stephan

**Comment by skullmonkey911** [comment]
Hi mjrgh,

I was right. Deaktivating HDR for my PF Monitor also resolved this issue. Strange. Why Popper Menu is more robust, I can't tell.  Somehow Pinbally has problem storing the coordinates if one monitor changes mode on exit.

I will give Pinbally now another chance, You gave useful input concerning the FX3 Modes ;) Thanks.

With kind regards,

Stephan

**Comment by mjrgh** [comment]
That sounds like a good discovery.   PinballY actually has no problem storing the coordinates when the monitor layout changes; it's that the layout has the be the same the next time it starts, because it has to be working against the same coordinate system.  If the saved coordinates mean something different at the start of the next session, you'll naturally get the windows in different positions - in other words, the windows will be placed at the positions that the saved coordinates represent in the **new** coordinate system at the start of the new session.

If you have a way to make sure that HDR is re-activated before PinballY starts, that should be all that's needed.  The important thing is that the saved coordinates mean the same thing at the start of the new session that they meant at the end of the last session.

**Comment by skullmonkey911** [comment]
So after have no problem direktly on the cab, I just found out that opening Pinbally via TeamViewer also messes all my screens up ;(

**Comment by mjrgh** [comment]
I'd guess that's because TeamViewer is also changing your desktop layout.

**Comment by mjrgh** [comment]
Here's a test build for you to try.  I added an option to disable the normal window position fixup that PinballY does at startup, which makes sure that each window is within the visible desktop.  To test this:

1. Make sure you have the 64-bit Beta 13 installed
2. Download the ZIP below
3. Unpack the files from the ZIP into your PinballY program folder, replacing the existing files
4. Run
5. Bring up the Settings dialog
6. Go to the Startup page
7. Un-check **Make sure all windows are positioned within the
   visible desktop area**
8. Click OK
9. Quit out of the program

Now try the various scenarios that were giving you problems with the window positioning - HDR, TeamViewer, anything else you ran into.

The new option lets you disable the normal window position check at startup.  I think that's probably what's behind the unwanted window repositioning you've been seeing.  Give it a try and let me know.

(This is the 64-bit version - let me know if you need the 32-bit version instead.)

[PinballY-20190528-NoWinRepos.zip](https://github.com/mjrgh/PinballY/files/3229979/PinballY-20190528-NoWinRepos.zip)

**Comment by skullmonkey911** [comment]
Hi mjrgh,

thanks for the debug verion, but unfortunatly this had no effect. Can I send you logs or something to look deeper into it?

Testing with TeamViewer:
What I can say is, positions are always kept, when positioning the (small not maximized) screens on the playfield. When I move them to the other display screens, everything is on the playfield again after restart

Regards,

Stephan.

**Comment by mjrgh** [comment]
Okay, that's too bad.  Just to confirm, you did **un-check** the option **Make sure all windows are positioned within the visible desktop area** before testing, right?

If I have any ideas for what to look for in the log, I'll let you know.  But I'm afraid I don't know what's going on if not this.

**Comment by skullmonkey911** [comment]
Hi,

OMG. This is a little embarrassing. I forgot to un-check... :( I think everything is fine with the debug version and unchecking the box. Tested it with Teamviewer just a sec ago.

Cheers Stephan

**Comment by mjrgh** [comment]
Great!  Glad you double-checked.  I'll mark this as closed, then.
