### ISSUE TITLE
Hi-scores not displaying for all supported games. 

### ISSUE THREAD

**Issue by Adeysan** [mjrgh/PinballY#74]
Issue:  Hi-scores are not showing for all supported games. 

E.g. (for me):

Theatre of Magic, Terminator 2, PotC, Power Play...  & more.

I confirmed the correct rom names were shown in the game setup screen, and also checked that scores could be retrieved OK for these roms via. Pinemhi command line.

I also discovered a workaround:  adding  ".nv" to the romname in the game setup screen seems to fix this issue (but causes another problem - the DMD no longer displays the scores in the same colour the DMD is set to in VPM - an (undocumented?) feature I really appreciate :)  ) 

I guess there is some issue passing the romnames to Pinemhi, but I cannot for the life of me see any connection between the few tables it affects  (for me, around 20 tables).

Thanks.

**Comment by mjrgh** [comment]
You definitely shouldn't be using the .nv suffix on the ROM names, since as you've noticed that causes separate problems.  

I guess I'll have to add some logging to help diagnose this, as it doesn't log much about it currently.  It would probably clarify the problem if we knew the exact PinEMHi command line being generated.

**Comment by mjrgh** [comment]
If you're still having problems with this, try the new logging in the beta 15 release.  Go to the Log File page in the settings and enable High Score Retrieval logging.  Then navigate to the problematic games.  Exit the program.  Look through PinballY.log for high-score details - that will walk you through the process that the system is using to form the names of the NV files and generate the PinEMHi command line.  Hopefully that will shed some light on what's going wrong on your system.  I suspect a configuration setting issue, so hopefully this will explain it and you can just make some simple changes and clear it up - but let me know if it looks like something wrong the system itself is doing.

**Comment by mjrgh** [comment]
Closing - I'm going to assume that whatever was going on was dealt with by inspecting the logs.
