### ISSUE TITLE
Additional status line variables

### ISSUE THREAD

**Issue by Adeysan** [mjrgh/PinballY#75]
I would like the possibility to show information on the status line which is otherwise only visible in each game’s “info box”. E.g.:

- Game rating
- Game type (EM, SS)
- Play count
- Play time
- Last played date/time
- Filename

This could be achieved with the additional of some new status line substitution variables:

- [Game.Rating]
- [Game.Playcount]. etc.

**Comment by mjrgh** [comment]
Implemented in the beta 15 release.
