### ISSUE TITLE
 can't find pbx's xml's

### ISSUE THREAD

**Issue by Daveytron** [mjrgh/PinballY#8]
When I run pinballY it can't find the xml's related to pbx

**Comment by mjrgh** [comment]
I'm afraid you're not giving me much to go on!  Please take a look at this and try to fill in some more detail base on those suggestions:

https://github.com/mjrgh/PinballY/wiki/How-to-write-a-good-bug-report

**Comment by Daveytron** [comment]
Ok what I did was double click on the pinbally icon and it started.
then It came up with this error 
![20180920_092911](https://user-images.githubusercontent.com/43398603/45787568-5e305e80-bcb9-11e8-969e-8b6465cbee70.jpg)
I have pbx installed but it can't find any tables.
Alos when I press 0 I get the menu without any text
![20180920_093029](https://user-images.githubusercontent.com/43398603/45787637-a9e30800-bcb9-11e8-8d61-e0e0b0ff096a.jpg) I'm runnung windows 7 on my main cab and it has diectx11 installed.
Hope this is enough information for you.
Btw what is the default Xml is it looking for and where.

**Comment by mjrgh** [comment]
Thanks for the information.  Here's something you can try to troubleshoot this yourself:

- Run PinballY
- right click in the main window
- select Options
- select the Log File section in the list on the left;
- make sure the box for "Player system setup and table searches" is checked
- click OK
- close the program

Now look at your PinballY.log file (in the main PinballY install folder).  It should have detailed information on how PinballY is looking for game files and databases.  Read through that and see if it tells you anything.  Hopefully that will give you enough information to see what's going wrong and make any needed settings adjustments.

If that doesn't solve it for you, I'll need to know more about your system setup to know where PinballY should be looking for files, where it's actually looking for files, and what files there are to find.  Ideally I could just trawl through your whole disk myself and see how things are set up, but that's obviously not possible, so here are some of the things that you could tell me to help me out:

1. Obvious question first:  do you have any games installed that it *should* be finding?

1a. When you run PinballX, what games does that program show you?

2. Where is PinballX installed (full folder path)?

3. What's in your PinballY Settings.txt file?  You can attach the file to the reply here.

4. What's in the PinballY.log file that you captured above?  You can also attach that to the reply.

5. What games do you have installed?

6. What systems do they use (Visual Pinball, Future Pinball, ...)?

7. Where are they installed?

**Comment by mjrgh** [comment]
You might also want to take a look at the "Files & Folders" section in the Help files.  That explains how the table lists are located.

**Comment by mjrgh** [comment]
This hasn't been updated in a long time, so I'm going to assume that either you're no longer using the program or you were able to solve the problem.  Feel free to reopen it necessary - please update the program to a current version when you retry so that we're all on the same page.
