### ISSUE TITLE
Table Images Upside down

### ISSUE THREAD

**Issue by sebinouse** [mjrgh/PinballY#9]
Every Table image is upside-down (flippers on the top) whatever orientation I use during drag&drop ... 

I tried to change orientation directly in the media folder without success.

**Comment by sebinouse** [comment]
I have the same result with two different orientations : 
![capture d ecran 2018-09-20 a 21 26 04](https://user-images.githubusercontent.com/9035443/45842080-f5c69900-bd1b-11e8-93bc-20a979a731fd.png)
![ac dc stern 2012](https://user-images.githubusercontent.com/9035443/45842169-29a1be80-bd1c-11e8-8284-4f0abee18ca2.jpg)
![ac dc stern 2012 old 1](https://user-images.githubusercontent.com/9035443/45842170-29a1be80-bd1c-11e8-8809-66a36c52711b.jpg)
I gonna try the capture now ...

**Comment by sebinouse** [comment]
My bad this a WIN10 error ... when I use "Photo" to rotate the image ... I don't know what it does but Explorer believe it has been rotated ... it might be a tag/exif or something

When I open the same image on my Mac the orientation is wrong !

DO NOT USE "PHOTO" TO ROTATE THE PICTURE ... my bad ! Sorry for that !

**Comment by mjrgh** [comment]
Ah, that makes sense.  I'll have to try to figure out what metadata they're inserting and see if my image loader can be made to respect that.

**Comment by mjrgh** [comment]
FYI, I've added recognition for the JPEG orientation marker, so rotations made through the Win 10 Photos app should work now.  (Added in Alpha 22.)
