### ISSUE TITLE
Backglass screen slow my playfield screen

### ISSUE THREAD

**Issue by Cley85** [mjrgh/PinballY#90]
Hi, i use a 75hz playfield screen and a 60hz backglass screen. When i turn the backglass screen, the table preview video enter in slow mod like 55 60fps. But when i turn the backglass off, the playfield preview return to 75hz. I can make a video if you want. 
I use win10 with a gtx 1060

**Comment by mjrgh** [comment]
I don't have any guess about what's going on.  One thing you might try is the "Lock frame rate to monitor refresh rate" option (under Options > Audio/Video).  Or turn it off if you tried turning it on.  I kind of doubt that has anything to do with it, but it might be worth a try - it might be that the frame rate is too high and saturating the video card.

**Comment by Cley85** [comment]
I have try with on and off and nothing change. I'm gonna make a video 😉

**Comment by Cley85** [comment]
https://youtu.be/DZ0QBgJJp94

**Comment by mjrgh** [comment]
Try a web search for **windows 10 problem with  different refresh rates** - it sounds like you might be running into a generic Win 10 Nvidia issue with multiple monitors.  It's not clear if there's a resolution.

**Comment by Cley85** [comment]
Not a win10 issue. Cause in game my playfield was at 75hz and backglass 60hz, see in my picture in corner https://zupimages.net/up/19/42/v7w1.jpg . By the way, thanks for all your hard work.

**Comment by mjrgh** [comment]
> Not a win10 issue

Did you actually do the search I suggested?

**Comment by Cley85** [comment]
Yes i have found lot of threads but in 2017, now all works via update . Btw i have tried pinup popper and backglass work at 60hz and playfield at 75hz, so definitely a pinballY issue 😕

**Comment by mjrgh** [comment]
Okay, wanted to check since that looked like the same symptom.  I don't have any other guesses at the moment.  Let me know if you figure anything out.

**Comment by mjrgh** [comment]
I'm going to mark this a cold case because I don't have any ideas on how to diagnose it.  Hopefully someone with a heterogeneous refresh rate system to test on will find this and pick it up.

It'd be interesting to try this on a mix of systems to see if...

- Is it Windows 10 only or all Win versions?
- Is it OP's card only or all Nvidia?
- Is it Nvidia only or ATI as well?

Best guess is an interaction between D3D11/DXGI and OP's video drivers, or maybe just D3D11/DXGI alone.  (I think the other programs OP tried against are D3D9.)  I'm not aware of any special handling needed at the D3D11 level for mixed refresh rate, but maybe there's something needed there.

**Comment by Cley85** [comment]
So, i have try another thing. I have use the integrated gpu to my motherboard for the backglass, and same result. Frame rate of the playfield drop to 60fps, and return to 75fps when i hide the backglass. Don't know if this can help you

**Comment by mjrgh** [comment]
That sounds like a good thing to have tried, at least.

I just wanted to double-check - you did try turning OFF the "lock frame rate" option, right?

**Comment by Cley85** [comment]
Yep i have turn it on an off and same result . I have try to launch 2 instance of pinballY, 1 for the playfield, and an other in the backglass screen, annnnnnnnnd fu..... The instance of the backglass run at 60fps and the playfield instance run at 75hz. So don't know if it possible to disassemble the playfield of the backglass of the dmd. But i think it's possible, if pinup work with different refresh rate, you can do the same. After that, just add the loading solution of kai cherry 😉😁. Thanks man 👌

**Comment by mjrgh** [comment]
One more question: what happens if you make both windows (playfield and backglass) really small, but keeping the placement on the two monitors the same?  

And then, if it still slows down, what happens when you move both windows onto the same monitor (the one with the higher native refresh rate)?

**Comment by Cley85** [comment]
I don't know if i understand what you say ( I'm a dumb French 😂) but if by really small you mean not fullscreen, it's the same, i have try fullscreen and in small window mod, and slowdown too. But when i set playfield and backglass to the same monitor (playfield monitor 75hz) the playfield preview work at 75fps and backglass preview at 60fps

**Comment by mjrgh** [comment]
Right, I meant "make the windows small", not full screen.

Very strange.  I wonder if you have some option enabled somewhere in your video driver setup that's locking the frame rate.  When "lock frame rate" is OFF in the PinballY setup, video normally runs much faster than the refresh rate - I get rates of about 200 fps with 1080p video, for example, on a 60Hz monitor.  The way your playback seems to lock to the slowest active monitor's physical refresh rate in all cases suggests that *something* in your system is doing the locking.  The "unlocked" frame rate is a function of your video card and CPU performance, but it seems extremely unlikely that it would just happen to match your monitor's physical refresh rate if it were GPU-bound or CPU-bound.  So it seems like something's doing the locking.  I don't know where you'd look for that, though.

**Comment by mjrgh** [comment]
Have you tried looking at your "Manage 3D Settings" in your NVIDIA control panel?  That might be where you're locking the rate.

**Comment by Cley85** [comment]
Yes i have try all i can in gpu settings, and it's definitely not a gpu issue, cause fx3 run the dmd on the backglass screen and my playfield run at 75fps

**Comment by Cley85** [comment]
And the bug appear when i use 2 gpu. So not a gpu settings

**Comment by mjrgh** [comment]
If you want a fix, you're going to have to trust me that it's your video settings.  I can't remote-administer your machine to figure out exactly what it is, but you've got one of the frame locking technlogies enabled - either VSYNC, GSYNC, or FreeSync.  The Nvidia setup should let you disable that on a program by program basis.  What you have to do is:

- Figure out which one of those you have enabled (maybe more than one)
- Disable it/them explicitly for PinballY.exe

**Comment by mjrgh** [comment]
Some articles that might help with that:

https://www.geforce.com/hardware/technology/adaptive-vsync/technology
https://www.howtogeek.com/270672/how-to-enable-optimize-and-tweak-nvidia-g-sync/

**Comment by Cley85** [comment]
Hmmmm why i can't change color option and run at 640x480 ? I can in all my application but not in pinballY

https://imgshare.io/image/vjL57

**Comment by mjrgh** [comment]
> Hmmmm why i can't change color option and run at 640x480 ? I can in all my application but not in pinballY

If you're thinking this is a solution for your frame rate problem, you're looking in the wrong place - you need to track down what's locking the frame rate as I explained above.

As for the 640x480 option being grayed out, you'll have to ask Microsoft.  At a guess, that's only enabled for old applications written for XP.  I don't think Windows supports that mode for newer applications.

**Comment by mjrgh** [comment]
Closed - no longer a factor for reporter (see #112).
