### ISSUE TITLE
Pause doesn't work

### ISSUE THREAD

**Issue by Cley85** [mjrgh/PinballY#92]
hi. when i presse the pause key in game, it just do nothing. 
i use visual pinball x in exclusive fullscreen and windows 10. 

i try it with exclusive fullscreen off and doesn't work too. 
i try with tons of different key and don't work too

and when I'm in game i can't acces the menu with "resume game, terminate game, instructions card, etc....."

thanks

**Comment by mjrgh** [comment]
I think it's using exclusive full-screen mode in VP that's the problem.  "Exclusive" means what it says - it means that VP has "exclusive" access to the screen, and no other programs can access it.  That's a hardware thing at the Windows level - PinballY can't take over the screen again as long as VPX is holding it hostage like that.  I recommend running WITHOUT exclusive full-screen mode in VP.  Use windowed full screen mode instead and you should have better luck.

**Comment by Cley85** [comment]
As i say, i have try with exclusive fullscreen off. And doesn't work too

**Comment by mjrgh** [comment]
Oh, I see.  

When you say this:

> when I'm in game i can't acces the menu with "resume game, ..."

Could you be more specific?  Lead me through the exact steps you're trying - down to the mouse click level, please.  I need to know exactly what you're trying to do here.

**Comment by Cley85** [comment]
If you presse esc key ( i have delete the exit key ) , you can have acces to a menu with "resume" "terminate game" "information" "instruction card" but this menu is near my vpx playfield. Why it doesn't show in the front ? Vpx is now in windowed screen and doesn't work better

**Comment by mjrgh** [comment]
I'm still not sure what you mean... please try to explain EXACTLY what you're doing.  Pretend I can't see your computer from here.

**Comment by Cley85** [comment]
Check this 😉
https://youtu.be/5W7NuIGHmCA

**Comment by mjrgh** [comment]
Thanks - that's helpful.  I'm not sure what could be going on.  It looks like PinballY is seeing the keystroke and switching itself back to the foreground, because you see it flash to the foreground momentarily each time, but then something is forcing VP back to the foreground.  (This is VP you're running, right?)  

Do you have any other software at all running in your system?  I'm thinking maybe something else is intervening and forcing VP back to the foreground.  Or maybe it's some setting you have in VP that keeps making it take control again.

**Comment by mjrgh** [comment]
Oh, I see what's going on... It's just a simple bug in PinballY itself.  I'll fix it for the next update.

**Comment by Cley85** [comment]
Cool man perfect 👌👍 im gonna wait your release 😎

**Comment by mjrgh** [comment]
This should be fixed in the beta 15.

**Comment by Cley85** [comment]
Man that's work perfect. Now need to improve video payback to 60fps without drops
