### ISSUE TITLE
Pinball FX3 Cabinet Code Gets Kicked

### ISSUE THREAD

**Issue by cherlihy71** [mjrgh/PinballY#94]
Randomly while using Pinbally (which I love btw ) and launching Pinball FX3 tables via steam using a cabinet code, sometimes causes Pinball FX3 code to gets wiped and you have to re-enter the cabinet code to go back to cabinet mode.

**Comment by mjrgh** [comment]
Hmm, I have no idea how that could be happening.  Maybe if you could find out how FX3 is storing the code that gets lost, I might be able to come up with some ideas.  And are you absolutely sure that it has something to do with PinballY, as opposed to some external cause, maybe a bug in FX3 itself?

**Comment by cherlihy71** [comment]
Not yet.  Doing some testing now and looking at the windows logs. It's starting to look like steam thought it was in use via another client, possibly my dev machine, and kicked it out of cabinet mode.  Once I have recreated the steps a few times, and if that's the case, maybe something to add to the wiki.  I let you know my findings.  Very much enjoying the ease of setup and how fast it runs.  I'm completely sold on it. Great work!

**Comment by cherlihy71** [comment]
After much testing, I can confirm this has nothing to do with PinballY.  It happened to me when 2 instances if Pinball FX3 via Steam were running under same account.

**Comment by mjrgh** [comment]
Thanks for the update - good luck tracking it down!
