### ISSUE TITLE
Zaccaria Pinball Support

### ISSUE THREAD

**Issue by cherlihy71** [mjrgh/PinballY#95]
I was wondering your thoughts on support for Zaccaria Pinball.

I'd assume setup would be close to Pinball FX3.

https://store.steampowered.com/app/444930/Zaccaria_Pinball/

**Comment by mjrgh** [comment]
Probably so.  You know how to set up a new system, right?  See the help section on Option Settings > Systems, under the heading "Add a new system".  If you're not sure about the parameters, maybe try asking on vpforums to see if anyone else knows the right settings.

**Comment by cherlihy71** [comment]
Currently their cabinet mode would have to accept a ton of key presses prior to getting to the table.  After some research, Zaccaria isn't really worth it for any frontend at the stage its in.

**Comment by mjrgh** [comment]
Sounds like the same deal as Farsight's The Pinball Arcade.  

There is an option in the System Setup dialog to send a sequence of keys to the game right after launching it.  That was designed around the need for this in TPA, but it never worked that well.  The exact sequence of keys wasn't 100% predictable (sometimes they'd pop up an ad dialog at launch, for example), and it was **really** twitchy about keystroke timing, so you had to slow down the key entry so much that it was painful to sit through - faster and easier just to do the navigation manually.  Plus they had a tendency to change their menu UI slightly on every release, so even when you got it working, you'd have to go fix it every time they pushed an update.  I think you're right that it's not worth the trouble until they offer a direct-to-table launch capability like FX2/FX3 does.
