### ISSUE TITLE
Button support lost after Zero Delay encoder changed.

### ISSUE THREAD

**Issue by cherlihy71** [mjrgh/PinballY#96]
Ok... weird thing happened tonight.  I decided to change out my generic usb zero delay encoder with a different one that supports LED buttons.

STEAM has been configured and all button presses work through STEAM (Pinball FX3), 'Microsoft Game Device Config/Properties (verified button presses)' and even GameEx PinballX works.  

However no button presses are being recognized by PinballY.  Even if I go to PinballY options, and attempt to bind a button, the button press is not showing when pressed, but it weirdly works with all other options mentioned above.   Any idea or am I missing a configuration step?

Thanks in advance!

**Comment by mjrgh** [comment]
Is it some kind of xbox-type controller?  I think some of those are incompatible with Raw Input, which is the Windows subsystem that PinballY uses to read joystick input.  Do you have a specific make or model?  Maybe try a google search for that make/model + "Raw Input" and see if there's any information about whether they work together.

**Comment by cherlihy71** [comment]
Thanks for the reply..  The encoder I switched to is:  https://www.amazon.com/gp/product/B07GJK3JDG

Previous working encoder was:  https://www.amazon.com/gp/product/B00UUROWWK

I switched for led button support in a single harness.  I am guessing Raw Input isn't supported by the newly switched encoder

**Comment by mjrgh** [comment]
I don't see much there in terms of technical documentation, so it's hard to guess what's it's using as a USB protocol. 

If you have Visual Studio installed, you could grab the C++ code, compile it, and poke around in the joystick code to see how (or if) it's showing up in the HID enumeration.

**Comment by mjrgh** [comment]
One more note: it's probably identifying itself as a game pad (USB usage page 1/usage 5) rather than a joystick (1/4), and PinballY's joystick code only recognizes joysticks.  I could try letting it recognize game pads as well - that might be enough to make it work, since joysticks and game pads are otherwise pretty similar in their USB layout.

**Comment by cherlihy71** [comment]
That would be awesome! Let me know if you release a beta for testing.  Would be happy to!

**Comment by mjrgh** [comment]
The change is in the new Beta 17.  Give it and try and let me know it makes any difference.  If not, I might try adding some instrumentation to see if we can figure out what the device looks like to USB.
