### ISSUE TITLE
Save Media Capture preferences in settings file for repeated actions

### ISSUE THREAD

**Issue by rtl19** [mjrgh/PinballY#98]
The media capture functions are wonderful.  I find myself always choosing the same actions even when others are selected.  This means I must constantly turn off the other items for each scan.  

For example, I always capture a playfield image, table audio, backglass image, dmd image.  However, when I go to a new table, table audio is always skipped, playfield video is always captured, backglass video is always captured, etc.  I'd like PinballY to give the option to save my preferences on skiping playfield video and backglass video.  This is just an example.  I'm sure other folks want other preferences.  Perhaps a set of templates would be useful.  Like: Still Image capture template or moving image capture template.  I'm just throwing ideas out there :)

**Comment by mjrgh** [comment]
The same settings that you used on the most recent capture should always be used on the next capture, as of Beta 15.  Assuming you're on Beta 15 or later, are you saying that's not happening?

**Comment by rtl19** [comment]
Correct.  That's not happening for me with Beta 18.  For example, I always turn off playfield video capture but with each table I go to, it is on by default.

**Comment by stojy** [comment]
I'm having the same problem. Those same media options are set to their default vales everytime.

**Comment by mjrgh** [comment]
What do you guys see if you do this:

- Run PinballY
- Do a capture with the settings you want
- Exit PinballY
- Open Settings.txt in notepad
- Look for lines of the form Capture.XXX.LastMode

What do you see there?  Does it match the mode you used in the last capture?

**Comment by rtl19** [comment]
It doesn't look like lastmode is being saved.  I turned off playfield video capture, backglass video capture and dmd video capture and these were the settings after exiting PinballY:

Capture.DMDVideo.LastMode = capture
Capture.PlayfieldAudio.LastMode = keep
Capture.PlayfieldVideo.LastMode = with_audio
Capture.PlayfieldImage.LastMode = capture
Capture.DMDImage.LastMode = capture
Capture.BackglassVideo.LastMode = capture
Capture.BackglassImage.LastMode = capture

**Comment by stojy** [comment]
Ditto for the batch capture settings.  They aren't being updated either.

Capture.PlayfieldImage.LastBatchReplace = 0
Capture.PlayfieldVideo.LastBatchReplace = 1
Capture.PlayfieldAudio.LastBatchReplace = 0
Capture.BackglassImage.LastBatchReplace = 0
Capture.BackglassVideo.LastBatchReplace = 1

**Comment by mjrgh** [comment]
This should be fixed now in Beta 19.
