### ISSUE TITLE
Table ratings don't appear in the edit details window.

### ISSUE THREAD

**Issue by rtl19** [mjrgh/PinballY#99]
I was expecting to be able to rate a table from 1-5 (like PinballX) in the edit details window.  Using the latest November Beta, I don't see that option.

**Comment by mjrgh** [comment]
Try "1" (Main Menu) -> Rate Table.

**Comment by rtl19** [comment]
You're fast!  :)  On my system choosing "1" immediately launches the game.  I might have remapped that button without realizing it.  I'll look into it.  I still think the the rating data point should be in the edit details window as well.

**Comment by rtl19** [comment]
I found it.  My "Enter" key brings up the main menu.

**Comment by rtl19** [comment]
I noticed the gamestats.csv has a field called rating.  Is that different that the Pinball X xml field with the same name?

Here is my xml snippet:
	<game name="Big Bang Bar (Capcom 1995)">
		<description>Big Bang Bar (Capcom 1995)</description>
		<rom>inactive_bbb109</rom>
		<manufacturer>Capcom</manufacturer>
		<year>1996</year>
		<type></type>
		<hidedmd>True</hidedmd>
		<hidetopper>True</hidetopper>
		<hidebackglass>False</hidebackglass>
		<enabled>True</enabled>
		**<rating>5</rating>**
	</game>

**Comment by mjrgh** [comment]
Kind of.  Pinball X doesn't allow half-star or zero ratings, so I had to store the information separately to preserve the additional information.
